// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b8829e3422fe27c74a1f4e07d56da7e614888fd639b55de913d8d33cbc54c3cf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    setupFiles: ["./setup.ts"],
  },
});
