# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8e0e5b57ae9d023a2b9410202e29285724656fd3a89414c101989e918f776e8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: contract
defmodule E2e.ContractTest do
  use ExUnit.Case, async: true

  describe "api_batch_bytes_async" do
    test "Tests async batch bytes extraction API (batch_extract_bytes)" do
      {:ok, result} = Kreuzberg.batch_extract_bytes_async("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert Enum.any?(["May 5, 2023", "Mallori"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "api_batch_bytes_sync" do
    test "Tests sync batch bytes extraction API (batch_extract_bytes_sync)" do
      {:ok, result} = Kreuzberg.batch_extract_bytes_sync("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert Enum.any?(["May 5, 2023", "Mallori"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "api_batch_bytes_with_configs_async" do
    test "Tests async batch bytes extraction with per-file configs (batch_extract_bytes with file_configs parameter)" do
      {:ok, result} = Kreuzberg.batch_extract_bytes_async("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.trim(result.output_format) == "markdown"
    end
  end

  describe "api_batch_bytes_with_configs_sync" do
    test "Tests sync batch bytes extraction with per-file configs (batch_extract_bytes_sync with file_configs parameter)" do
      {:ok, result} = Kreuzberg.batch_extract_bytes_sync("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.trim(result.output_format) == "markdown"
    end
  end

  describe "api_batch_file_async" do
    test "Tests async batch file extraction API (batch_extract_file)" do
      {:ok, result} = Kreuzberg.batch_extract_file_async("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert Enum.any?(["May 5, 2023", "Mallori"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "api_batch_file_sync" do
    test "Tests sync batch file extraction API (batch_extract_file_sync)" do
      {:ok, result} = Kreuzberg.batch_extract_file_sync("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert Enum.any?(["May 5, 2023", "Mallori"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "api_batch_file_with_configs_async" do
    test "Tests async batch file extraction with per-file configs (batch_extract_files with file_configs parameter)" do
      {:ok, result} = Kreuzberg.batch_extract_file_async("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.trim(result.output_format) == "markdown"
    end
  end

  describe "api_batch_file_with_configs_sync" do
    test "Tests sync batch file extraction with per-file configs (batch_extract_files_sync with file_configs parameter)" do
      {:ok, result} = Kreuzberg.batch_extract_file_sync("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.trim(result.output_format) == "markdown"
    end
  end

  describe "api_batch_file_with_timeout_sync" do
    test "Tests sync batch file extraction with per-file timeout config override" do
      {:ok, result} = Kreuzberg.batch_extract_file_sync("pdf/fake_memo.pdf", %{"extraction_timeout_secs" => 300})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
    end
  end

  describe "api_extract_bytes_async" do
    test "Tests async bytes extraction API (extract_bytes)" do
      {:ok, result} = Kreuzberg.extract_bytes_async("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert Enum.any?(["May 5, 2023", "Mallori"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "api_extract_bytes_sync" do
    test "Tests sync bytes extraction API (extract_bytes_sync)" do
      {:ok, result} = Kreuzberg.extract_bytes_sync("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert Enum.any?(["May 5, 2023", "Mallori"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "api_extract_file_async" do
    test "Tests async file extraction API (extract_file)" do
      {:ok, result} = Kreuzberg.extract_file_async("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert Enum.any?(["May 5, 2023", "Mallori"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "api_extract_file_sync" do
    test "Tests sync file extraction API (extract_file_sync)" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert Enum.any?(["May 5, 2023", "Mallori"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "config_acceleration_cpu_provider" do
    test "Tests explicit CPU acceleration provider configuration" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"acceleration" => %{"device_id" => 0, "provider" => "cpu"}})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 50
      assert Enum.any?(["May 5, 2023", "To Whom it May Concern"], fn v -> String.contains?(to_string(result.content), v) end)
    end
  end

  describe "config_chunking" do
    test "Tests chunking configuration with chunk assertions" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"chunking" => %{"max_chars" => 500, "max_overlap" => 50}})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert length(result.chunks) >= 1
      assert result.chunks_have_content == true
    end
  end

  describe "config_chunking_text" do
    test "Tests text chunker type (generic whitespace/punctuation splitter)" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"chunking" => %{"chunker_type" => "text", "max_chars" => 500, "max_overlap" => 50}})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert length(result.chunks) >= 1
      assert result.chunks_have_content == true
    end
  end

  describe "config_disable_ocr" do
    test "Tests disable_ocr configuration option - OCR is skipped for images" do
      {:ok, result} = Kreuzberg.extract_file_sync("images/test_hello_world.png", %{"disable_ocr" => true})
      assert String.trim(result.mime_type) == "image/png"
      assert String.length(result.content) <= 5
    end
  end

  describe "config_document_structure" do
    test "Tests include_document_structure config produces document tree" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"include_document_structure" => true})
      assert String.trim(result.mime_type) == "application/pdf"
      assert result.document_structure != ""
      assert length(result.document_structure.nodes) >= 1
      assert String.contains?(to_string(result.document_structure.node_types), "paragraph")
    end
  end

  describe "config_document_structure_disabled" do
    test "Tests document field is null when include_document_structure is false" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
    end
  end

  describe "config_document_structure_with_headings" do
    test "Tests document structure with DOCX heading-driven nesting" do
      {:ok, result} = Kreuzberg.extract_file_sync("docx/fake.docx", %{"include_document_structure" => true})
      assert String.trim(result.mime_type) == "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      assert result.document_structure != ""
      assert length(result.document_structure.nodes) >= 1
    end
  end

  describe "config_email_msg_fallback_codepage" do
    test "Tests MSG extraction with custom fallback codepage for Cyrillic" do
      {:ok, result} = Kreuzberg.extract_file_async("email/fake_email.msg", %{"email" => %{"msg_fallback_codepage" => 1251}})
      assert String.trim(result.mime_type) == "application/vnd.ms-outlook"
      assert String.length(result.content) >= 10
    end
  end

  describe "config_extraction_timeout" do
    test "Tests that extraction_timeout_secs config field is accepted and does not affect fast extractions" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"extraction_timeout_secs" => 300})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
    end
  end

  describe "config_html_options" do
    test "Tests extraction with HTML conversion options configured" do
      {:ok, result} = Kreuzberg.extract_file_sync("html/complex_table.html", %{"html_options" => %{"extract_metadata" => true}})
      assert Enum.any?(["text/html"], fn v -> String.contains?(to_string(result.mime_type), v) end)
      assert String.length(result.content) >= 10
      assert result.content != ""
    end
  end

  describe "config_html_styled_custom_css" do
    test "HTML output with inline user CSS string is embedded verbatim in the style block" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"html_output" => %{"css" => ".kb-p { color: red; }", "embed_css" => true, "theme" => "unstyled"}, "output_format" => "html"})
      assert String.trim(result.output_format) == "html"
      assert String.contains?(to_string(result.content), ".kb-p { color: red; }")
      assert String.contains?(to_string(result.content), "kb-doc")
    end
  end

  describe "config_html_styled_default" do
    test "HTML output with default theme emits kb-* class hooks and an embedded style block" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"html_output" => %{"embed_css" => true, "theme" => "default"}, "output_format" => "html"})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.trim(result.output_format) == "html"
      assert String.contains?(to_string(result.content), "kb-doc")
      assert String.contains?(to_string(result.content), "kb-content")
      assert String.contains?(to_string(result.content), "kb-p")
      assert String.contains?(to_string(result.content), "<style>")
    end
  end

  describe "config_html_styled_no_embed" do
    test "HTML output with embed_css false emits class hooks but no style block" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"html_output" => %{"embed_css" => false, "theme" => "default"}, "output_format" => "html"})
      assert String.trim(result.output_format) == "html"
      assert String.contains?(to_string(result.content), "kb-doc")
      assert String.contains?(to_string(result.content), "kb-content")
    end
  end

  describe "config_images" do
    test "Tests image extraction configuration with image assertions" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/embedded_images_tables.pdf", %{"images" => %{"extract_images" => true}})
      assert String.trim(result.mime_type) == "application/pdf"
      assert length(result.images) >= 1
    end
  end

  describe "config_images_with_formats" do
    test "Tests image extraction on PPTX containing embedded images" do
      {:ok, result} = Kreuzberg.extract_file_sync("pptx/powerpoint_with_image.pptx", %{"images" => %{"extract_images" => true}})
      assert String.trim(result.mime_type) == "application/vnd.openxmlformats-officedocument.presentationml.presentation"
      assert length(result.images) >= 1
    end
  end

  describe "config_language_detection" do
    test "Tests language detection configuration" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"language_detection" => %{"enabled" => true}})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.contains?(to_string(result.detected_languages), "eng")
      assert result.language_detection_confidence >= 0.5
    end
  end

  describe "config_language_detection_multi" do
    test "Tests language detection with detect_multiple and min_confidence options" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"language_detection" => %{"detect_multiple" => true, "enabled" => true, "min_confidence" => 0.3}})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.contains?(to_string(result.detected_languages), "eng")
    end
  end

  describe "config_postprocessor" do
    test "Tests postprocessor config is accepted and extraction succeeds" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"postprocessor" => %{"enabled" => true}})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert result.content != ""
    end
  end

  describe "config_processing_warnings_empty" do
    test "Tests that a clean PDF extraction produces no processing warnings" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf")
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert is_nil(result.processing_warnings) or String.trim(result.processing_warnings) == ""
    end
  end

  describe "config_quality_disabled" do
    test "Tests extraction with quality processing explicitly disabled" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"enable_quality_processing" => false})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert result.content != ""
    end
  end

  describe "config_security_limits" do
    test "Tests archive extraction with custom security limits" do
      {:ok, result} = Kreuzberg.extract_file_sync("archives/documents.zip", %{"security_limits" => %{"max_archive_size" => 104857600, "max_compression_ratio" => 50, "max_files_in_archive" => 100}})
      assert Enum.any?(["application/zip", "application/x-zip-compressed"], fn v -> String.contains?(to_string(result.mime_type), v) end)
      assert String.length(result.content) >= 10
    end
  end

  describe "config_tables_content" do
    test "Tests table extraction with content_contains_any assertion on DOCX with tables" do
      {:ok, result} = Kreuzberg.extract_file_sync("docx/docx_tables.docx")
      assert String.trim(result.mime_type) == "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      assert length(result.tables) >= 1
    end
  end

  describe "config_use_cache_false" do
    test "Tests use_cache=false configuration option" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"use_cache" => false})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
    end
  end

  describe "output_format_bytes_markdown" do
    test "Tests markdown output format via bytes extraction API" do
      {:ok, result} = Kreuzberg.extract_bytes_sync("pdf/fake_memo.pdf", %{"output_format" => "markdown"})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.trim(result.output_format) == "markdown"
    end
  end

  describe "output_format_djot" do
    test "Tests Djot output format" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"output_format" => "djot"})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.trim(result.output_format) == "djot"
    end
  end

  describe "output_format_html" do
    test "Tests HTML output format" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"output_format" => "html"})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.trim(result.output_format) == "html"
    end
  end

  describe "output_format_markdown" do
    test "Tests Markdown output format" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"output_format" => "markdown"})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.trim(result.output_format) == "markdown"
    end
  end

  describe "output_format_plain" do
    test "Tests Plain output format" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"output_format" => "plain"})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.trim(result.output_format) == "plain"
    end
  end

  describe "result_format_element_based" do
    test "Tests ElementBased result format with element assertions" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"result_format" => "element_based"})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.trim(result.result_format) == "element_based"
      assert length(result.elements) >= 1
    end
  end

  describe "result_format_unified" do
    test "Tests Unified result format (default)" do
      {:ok, result} = Kreuzberg.extract_file_sync("pdf/fake_memo.pdf", %{"result_format" => "unified"})
      assert String.trim(result.mime_type) == "application/pdf"
      assert String.length(result.content) >= 10
      assert String.trim(result.result_format) == "unified"
    end
  end
end
