# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3c554e9883abf65e27bc1d7d8acca874e97912e669b29698bfe65b642c9fd818
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embeddings
defmodule E2e.EmbeddingsTest do
  use ExUnit.Case, async: false

  describe "embed_texts_different_preset" do
    test "embed_texts_different_preset" do
      {:ok, result} = Kreuzberg.embed_texts("[\"Hello world\",\"Test\"]", "{\"embedding_model\":\"multilingual\"}")
      assert length(result) >= 2
    end
  end

  describe "get_embedding_preset_known" do
    test "get_embedding_preset_known" do
      result = Kreuzberg.get_embedding_preset("default")
    end
  end

  describe "get_embedding_preset_nominal" do
    test "get_embedding_preset_nominal" do
      result = Kreuzberg.get_embedding_preset("default")
    end
  end

  describe "get_embedding_preset_unknown" do
    test "get_embedding_preset_unknown" do
      result = Kreuzberg.get_embedding_preset("nonexistent-xyz")
      assert is_nil(result) or String.trim(result) == ""
    end
  end

  describe "list_embedding_presets_sanity" do
    test "list_embedding_presets_sanity" do
      result = Kreuzberg.list_embedding_presets(%{})
      assert result != ""
    end
  end
end
