# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7ab8b31b2f87f919c5f7e3e4fe604a0c86f6c21dbf792c30b0c63b355b1fd193
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: format_specific
defmodule E2e.FormatSpecificTest do
  use ExUnit.Case, async: false

  describe "format_docx_standalone" do
    @tag :skip
    test "format_docx_standalone" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "format_pdf_text" do
    @tag :skip
    test "format_pdf_text" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "format_pptx" do
    @tag :skip
    test "format_pptx" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "format_xlsx" do
    @tag :skip
    test "format_xlsx" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
