# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: string_utils
defmodule E2e.StringUtilsTest do
  use ExUnit.Case, async: true

  describe "camel_to_snake_basic" do
    test "Convert camelCase to snake_case" do
      {:ok, result} = Kreuzberg.extract_file_async("")
      assert String.trim(result.result) == "my_variable_name"
    end
  end

  describe "camel_to_snake_single" do
    test "Convert single word (no camelCase) remains unchanged" do
      {:ok, result} = Kreuzberg.extract_file_async("")
      assert String.trim(result.result) == "hello"
    end
  end

  describe "sanitize_filename_basic" do
    test "Sanitize path traversal attempts in filename" do
      {:ok, result} = Kreuzberg.extract_file_async("")
      assert String.length(result.result) >= 1
    end
  end

  describe "sanitize_filename_special" do
    test "Sanitize special characters in filename" do
      {:ok, result} = Kreuzberg.extract_file_async("")
      assert String.length(result.result) >= 1
    end
  end

  describe "sanitize_path_basic" do
    test "Sanitize path traversal in file path" do
      {:ok, result} = Kreuzberg.extract_file_async("../../../secret/file.txt")
      assert String.length(result.result) >= 1
    end
  end

  describe "sanitize_path_spaces" do
    test "Sanitize path with spaces" do
      {:ok, result} = Kreuzberg.extract_file_async("my folder/file.txt")
    end
  end

  describe "sanitize_path_traversal" do
    test "Sanitize path traversal" do
      {:ok, result} = Kreuzberg.extract_file_async("../../../etc/passwd")
    end
  end

  describe "snake_to_camel_basic" do
    test "Convert snake_case to camelCase" do
      {:ok, result} = Kreuzberg.extract_file_async("")
      assert String.trim(result.result) == "myVariableName"
    end
  end

  describe "snake_to_camel_single" do
    test "Convert single word remains unchanged" do
      {:ok, result} = Kreuzberg.extract_file_async("")
      assert String.trim(result.result) == "hello"
    end
  end
end
