# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8a789ad83acbf457fc50df4569265510af69d5992f29a895c291e93f7f24ee3d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: table
defmodule E2e.TableTest do
  use ExUnit.Case, async: false

  describe "table_csv_extraction" do
    @tag :skip
    test "CSV file extraction produces content" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "table_html_extraction" do
    @tag :skip
    test "HTML table extraction produces markdown format" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "table_xlsx_markdown" do
    @tag :skip
    test "XLSX extraction produces markdown table format" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
