// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:805fb46e796e14a5ca716c7d931b37db6a75e992109a22b00b3eb8e176ec1a2f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: detection.</summary>
public class DetectionTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_DetectMimeBytesHtml()
    {
        // Detect HTML MIME from bytes
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_DetectMimeBytesPdf()
    {
        // Detect PDF MIME type from bytes
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_DetectMimeBytesPng()
    {
        // Detect PNG MIME type from bytes
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_GetExtensionsUnknownMime()
    {
        // get_extensions unknown MIME
    }
}
