// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:db8aaea02e82872c0d28616954655e7da15f81e2f9a6eb8da650a6adb7456d0e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: format_specific.</summary>
public class FormatSpecificTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_FormatCsv()
    {
        // CSV file extraction using extract_file_sync
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_FormatDocxStandalone()
    {
        // Standalone DOCX extraction using extract_bytes_sync
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_FormatEmailEml()
    {
        // Email EML file extraction using extract_file_sync
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_FormatPdfText()
    {
        // Standalone PDF text extraction using extract_bytes_sync
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_FormatPptx()
    {
        // PPTX presentation extraction using extract_bytes_sync
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_FormatRtf()
    {
        // RTF file extraction using extract_file_sync
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_FormatXlsx()
    {
        // XLSX spreadsheet extraction using extract_bytes_sync
    }
}
