// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b353e2482f32018ca2a2a7caa41a03d2aede8330ee4488ec8f35ed7e74833328
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: smoke.</summary>
public class SmokeTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_SmokeDocxBasic()
    {
        // Smoke test: DOCX with formatted text
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_SmokeHtmlBasic()
    {
        // Smoke test: HTML table extraction
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_SmokeJsonBasic()
    {
        // Smoke test: JSON file extraction
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_SmokePdfBasic()
    {
        // Smoke test: PDF with simple text extraction
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_SmokeTxtBasic()
    {
        // Smoke test: Plain text file
    }

    [Fact(Skip = "non-HTTP fixture: C# binding does not expose a callable for the configured `[e2e.call]` function")]
    public void Test_SmokeXlsxBasic()
    {
        // Smoke test: XLSX with basic spreadsheet data including tables
    }
}
