// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:339d3eac62aa91c883053180eb14a445f748752789b9a0fe1d42ca0e97d4dc83
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: text_processing.</summary>
public class TextProcessingTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public void Test_TextCleanExtracted()
    {
        // Extract and clean text content from document
        var result = Kreuzberg.ExtractFileSync("json/simple.json", null, null);
        Assert.True(result.Content.Length >= 5, "expected length >= 5");
    }

    [Fact]
    public void Test_TextNormalizeWhitespace()
    {
        // Extract text with whitespace normalization (no consecutive spaces)
        var result = Kreuzberg.ExtractFileSync("pdf/fake_memo.pdf", null, null);
        Assert.DoesNotContain("  ", result.Content.ToString());
    }
}
