// This file is auto-generated by alef. DO NOT EDIT.
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;

namespace Kreuzberg.E2e;

/// <summary>E2e tests for category: validation.</summary>
public class ValidationTests
{
    private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

    [Fact]
    public async Task Test_ValidateConfidenceFnInvalid()
    {
        // Reject confidence threshold > 1.0
        await Assert.ThrowsAsync<KreuzbergException>(() => Kreuzberg.ExtractFile("", null, null));
    }

    [Fact]
    public async Task Test_ValidateConfidenceFnValid()
    {
        // Accept valid confidence threshold
        var result = await Kreuzberg.ExtractFile("", null, null);
    }

    [Fact]
    public async Task Test_ValidateFormatInvalid()
    {
        // Reject invalid output format
        await Assert.ThrowsAsync<KreuzbergException>(() => Kreuzberg.ExtractFile("", null, null));
    }

    [Fact]
    public async Task Test_ValidateFormatValid()
    {
        // Accept valid output format
        var result = await Kreuzberg.ExtractFile("", null, null);
    }

    [Fact]
    public async Task Test_ValidateHostValid()
    {
        // Accept valid host address
        var result = await Kreuzberg.ExtractFile("", null, null);
    }

    [Fact]
    public async Task Test_ValidateLangInvalid()
    {
        // Reject invalid language code
        await Assert.ThrowsAsync<KreuzbergException>(() => Kreuzberg.ExtractFile("", null, null));
    }

    [Fact]
    public async Task Test_ValidateLangValid()
    {
        // Accept valid language code
        var result = await Kreuzberg.ExtractFile("", null, null);
    }

    [Fact]
    public async Task Test_ValidateMimeInvalid()
    {
        // Reject invalid MIME type
        await Assert.ThrowsAsync<KreuzbergException>(() => Kreuzberg.ExtractFile("", "invalid", null));
    }

    [Fact]
    public async Task Test_ValidateMimeValid()
    {
        // Accept valid MIME type
        var result = await Kreuzberg.ExtractFile("", "application/pdf", null);
    }

    [Fact]
    public async Task Test_ValidateOemInvalid()
    {
        // Reject invalid Tesseract OEM mode
        await Assert.ThrowsAsync<KreuzbergException>(() => Kreuzberg.ExtractFile("", null, null));
    }

    [Fact]
    public async Task Test_ValidateOemValid()
    {
        // Accept valid Tesseract OEM mode
        var result = await Kreuzberg.ExtractFile("", null, null);
    }

    [Fact]
    public async Task Test_ValidatePortInvalid()
    {
        // Reject invalid port number (zero)
        await Assert.ThrowsAsync<KreuzbergException>(() => Kreuzberg.ExtractFile("", null, null));
    }

    [Fact]
    public async Task Test_ValidatePortValid()
    {
        // Accept valid port number
        var result = await Kreuzberg.ExtractFile("", null, null);
    }

    [Fact]
    public async Task Test_ValidatePsmInvalid()
    {
        // Reject invalid Tesseract PSM mode
        await Assert.ThrowsAsync<KreuzbergException>(() => Kreuzberg.ExtractFile("", null, null));
    }

    [Fact]
    public async Task Test_ValidatePsmValid()
    {
        // Accept valid Tesseract PSM mode
        var result = await Kreuzberg.ExtractFile("", null, null);
    }
}
