// This file is auto-generated by alef. DO NOT EDIT.
//! E2e tests for category: serialization

use kreuzberg::{serialize_to_json, serialize_to_toon};

#[test]
fn test_serialize_json_basic() {
    // Serialize extraction result to JSON
    let path = r#"test_documents/text/plain.txt"#;
    let config_json = serde_json::json!({});
    let config = Some(serde_json::from_value(config_json).unwrap());
    let result = serialize_to_json(&path, &config).expect("should succeed");
    assert!(
        result.content.len() >= 1,
        "expected length >= 1, got {}",
        result.content.len()
    );
}

#[test]
fn test_serialize_json_pdf() {
    // Serialize PDF extraction to JSON
    let path = r#"test_documents/pdf/sample.pdf"#;
    let config_json = serde_json::json!({});
    let config = Some(serde_json::from_value(config_json).unwrap());
    let result = serialize_to_json(&path, &config).expect("should succeed");
    let content = result.content.as_deref().unwrap_or("");
    assert!(
        format!("{:?}", content).contains(r#"content"#),
        "expected to contain: {}",
        r#"content"#
    );
}

#[test]
fn test_serialize_toon_basic() {
    // Serialize extraction result to TOON format
    let path = r#"test_documents/text/plain.txt"#;
    let config_json = serde_json::json!({});
    let config = Some(serde_json::from_value(config_json).unwrap());
    let result = serialize_to_toon(&path, &config).expect("should succeed");
    assert!(
        result.content.len() >= 1,
        "expected length >= 1, got {}",
        result.content.len()
    );
}

#[test]
fn test_serialize_toon_pdf() {
    // Serialize PDF extraction to TOON
    let path = r#"test_documents/pdf/sample.pdf"#;
    let config_json = serde_json::json!({});
    let config = Some(serde_json::from_value(config_json).unwrap());
    let result = serialize_to_toon(&path, &config).expect("should succeed");
    assert!(
        result.content.len() >= 10,
        "expected length >= 10, got {}",
        result.content.len()
    );
}
