// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:39e8d536722bc80ca7c61495c0440ec1ad21bde573a5344d31eb61d7d837574d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: uri

use kreuzberg::classify_uri;

#[test]
fn test_classify_uri_anchor() {
    // Classify fragment URI
    let url = r#"#section-header"#;
    let _ = classify_uri(&url);
}

#[test]
fn test_classify_uri_email() {
    // Classify mailto URI
    let url = r#"mailto:user@example.com"#;
    let _ = classify_uri(&url);
}

#[test]
fn test_classify_uri_https() {
    // Classify HTTPS URL
    let url = r#"https://example.com/page"#;
    let _ = classify_uri(&url);
}
