<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7c0f71263e269c13d54fd3f741a7f49e797a59bf5f978145f60ea82d5a726c70
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: detection. */
final class DetectionTest extends TestCase
{
    /** Detect JPEG from bytes */
    public function test_detect_image_jpeg(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_image_format("/9j/4AAQ");
    }

    /** Detect PNG image format */
    public function test_detect_image_png(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_image_format("images/hello_world.png");
    }

    /** Detect English language in text */
    public function test_detect_lang_english(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_languages("The quick brown fox jumps over the lazy dog.");
    }

    /** Detect French language in text */
    public function test_detect_lang_french(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_languages("Bonjour le monde, comment allez-vous aujourd'hui?");
    }

    /** Detect mixed languages in text */
    public function test_detect_lang_mixed(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_languages("Hello world. Bonjour le monde. Hallo Welt.");
    }

    /** Detect HTML MIME from bytes */
    public function test_detect_mime_bytes_html(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_mime_type_from_bytes("<!DOCTYPE html><html><body>Hello</body></html>");
    }

    /** Detect PDF MIME type from bytes */
    public function test_detect_mime_bytes_pdf(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_mime_type_from_bytes("pdf/fake_memo.pdf");
    }

    /** Detect PNG MIME type from bytes */
    public function test_detect_mime_bytes_png(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_mime_type_from_bytes("images/hello_world.png");
    }

    /** Detect DOCX MIME type from extension */
    public function test_detect_mime_docx(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_mime_type("document.docx");
    }

    /** Detect HTML MIME type from extension */
    public function test_detect_mime_html(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_mime_type("page.html");
    }

    /** detect_mime_type file not found */
    public function test_detect_mime_not_found(): void
    {
        $this->expectException(\Exception::class);
        Kreuzberg\Kreuzberg::detect_mime_type("/nonexistent/path/file.pdf", true);
    }

    /** Detect PDF MIME type from extension */
    public function test_detect_mime_pdf(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_mime_type("test.pdf");
    }

    /** detect_mime_type unknown extension */
    public function test_detect_mime_unknown_ext(): void
    {
        $this->expectException(\Exception::class);
        Kreuzberg\Kreuzberg::detect_mime_type("file.zzz_unknown");
    }

    /** detect_or_validate with both */
    public function test_detect_or_validate_both(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_or_validate("file.pdf", "application/pdf");
    }

    /** detect_or_validate unsupported MIME */
    public function test_detect_or_validate_invalid_mime(): void
    {
        $this->expectException(\Exception::class);
        Kreuzberg\Kreuzberg::detect_or_validate("application/x-nonexistent");
    }

    /** Validate known MIME */
    public function test_detect_or_validate_mime(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_or_validate("application/pdf");
    }

    /** detect_or_validate errors with no args */
    public function test_detect_or_validate_neither(): void
    {
        $this->expectException(\Exception::class);
        Kreuzberg\Kreuzberg::detect_or_validate();
    }

    /** Detect MIME from path */
    public function test_detect_or_validate_path(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::detect_or_validate("document.pdf");
    }

    /** get_extensions unknown MIME */
    public function test_get_extensions_unknown_mime(): void
    {
        $this->expectException(\Exception::class);
        Kreuzberg\Kreuzberg::get_extensions_for_mime("application/x-totally-unknown");
    }

    /** Invalid format field */
    public function test_is_valid_format_field_false(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::is_valid_format_field("nonexistent_field_xyz");
    }

    /** Valid format field */
    public function test_is_valid_format_field_true(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::is_valid_format_field("content");
    }
}
