<?php
// This file is auto-generated by alef. DO NOT EDIT.

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: hash. */
final class HashTest extends TestCase
{
    /** Hash PDF bytes using BLAKE3 */
    public function test_blake3_bytes_pdf(): void
    {
        $result = Kreuzberg\Kreuzberg::blake3_hash_bytes("pdf/fake_memo.pdf");
        $this->assertGreaterThanOrEqual(64, strlen($result));
    }

    /** Hash text file bytes using BLAKE3 */
    public function test_blake3_bytes_text(): void
    {
        $result = Kreuzberg\Kreuzberg::blake3_hash_bytes("text/plain.txt");
        $this->assertGreaterThanOrEqual(64, strlen($result));
    }

    /** blake3_hash_file nonexistent file */
    public function test_blake3_file_not_found(): void
    {
        $this->expectException(\Exception::class);
        Kreuzberg\Kreuzberg::blake3_hash_file("nonexistent/file.pdf");
    }

    /** Hash PDF file using BLAKE3 */
    public function test_blake3_file_pdf(): void
    {
        $result = Kreuzberg\Kreuzberg::blake3_hash_file("pdf/fake_memo.pdf");
        $this->assertGreaterThanOrEqual(64, strlen($result));
    }

    /** Hash text file using BLAKE3 */
    public function test_blake3_file_text(): void
    {
        $result = Kreuzberg\Kreuzberg::blake3_hash_file("text/plain.txt");
        $this->assertGreaterThanOrEqual(64, strlen($result));
    }

    /** Compute hash for PDF file */
    public function test_compute_hash_basic(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::compute_hash("pdf/fake_memo.pdf");
    }

    /** Hash different content */
    public function test_compute_hash_different(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::compute_hash("different content");
    }

    /** Hash PDF file using fast hash */
    public function test_fast_hash_basic(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::fast_hash("pdf/fake_memo.pdf");
    }

    /** Hash empty bytes */
    public function test_fast_hash_empty(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::fast_hash("");
    }
}
