<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:86fdc2d500c81a9cd34ccd631865709c5d897194c1ff63855a69da24896d82e4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: parsing. */
final class ParsingTest extends TestCase
{
    /** Parse JSON document format */
    public function test_parse_json(): void
    {
        $result = Kreuzberg\Kreuzberg::extract_file_sync("json/simple.json");
        $this->assertGreaterThanOrEqual(5, strlen($result->content));
    }

    /** Parse TOML document format */
    public function test_parse_toml(): void
    {
        $result = Kreuzberg\Kreuzberg::extract_file_sync("data_formats/cargo.toml");
        $this->assertGreaterThanOrEqual(5, strlen($result->content));
    }

    /** Parse XML document format */
    public function test_parse_xml(): void
    {
        $result = Kreuzberg\Kreuzberg::extract_file_sync("xml/simple_note.xml");
        $this->assertGreaterThanOrEqual(5, strlen($result->content));
    }

    /** Parse YAML document format */
    public function test_parse_yaml(): void
    {
        $result = Kreuzberg\Kreuzberg::extract_file_sync("test_fixtures/config.yaml");
        $this->assertGreaterThanOrEqual(5, strlen($result->content));
    }
}
