<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8571204f780b0efbb1a3ca95bd3cb043c7b73a1a516116fca4478410ab613fb7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: registry_operations. */
final class RegistryOperationsTest extends TestCase
{
    /** Get file extensions for DOCX MIME type */
    public function test_extensions_docx(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::get_extensions_for_mime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
    }

    /** Get file extensions for HTML MIME type */
    public function test_extensions_html(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::get_extensions_for_mime("text/html");
    }

    /** Get file extensions for PDF MIME type */
    public function test_extensions_pdf(): void
    {
        $result = Kreuzberg::get_extensions_for_mime("application/pdf");
        $this->assertStringContainsString("pdf", $result);
    }
}
