// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Email metadata extracted from .eml and .msg files.
 *
 * Includes sender/recipient information, message ID, and attachment list.
 */
data class EmailMetadata(
    /**
     * Sender's email address
     */
    val fromEmail: String?,
    /**
     * Sender's display name
     */
    val fromName: String?,
    /**
     * Primary recipients
     */
    val toEmails: List<String>,
    /**
     * CC recipients
     */
    val ccEmails: List<String>,
    /**
     * BCC recipients
     */
    val bccEmails: List<String>,
    /**
     * Message-ID header value
     */
    val messageId: String?,
    /**
     * List of attachment filenames
     */
    val attachments: List<String>,
)
