// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * Hierarchical level of an OCR element.
 *
 * Maps to Tesseract's page segmentation hierarchy and provides
 * equivalent semantics for PaddleOCR.
 */
enum class OcrElementLevel {
    /**
     * Individual word
     */
    WORD,

    /**
     * Line of text (default for PaddleOCR)
     */
    LINE,

    /**
     * Paragraph or text block
     */
    BLOCK,

    /**
     * Page-level element
     */
    PAGE,
}
