// Generated by alef. Do not edit by hand.

package dev.kreuzberg

/**
 * A URI extracted from a document.
 *
 * Represents any link, reference, or resource pointer found during extraction.
 * The `kind` field classifies the URI semantically, while `label` carries
 * optional human-readable display text.
 */
data class Uri(
    /**
     * The URL or path string.
     */
    val url: String,
    /**
     * Optional display text / label for the link.
     */
    val label: String?,
    /**
     * Optional page number where the URI was found (1-indexed).
     */
    val page: Int?,
    /**
     * Semantic classification of the URI.
     */
    val kind: UriKind,
)
