# frozen_string_literal: true

require "rspec/core/rake_task"

task default: :spec

RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = "spec/**/*_spec.rb"
  t.rspec_opts = "--color --format progress"
end

task test: :spec

desc "Run RSpec with verbose output"
task :spec_verbose do
  RSpec::Core::RakeTask.new(:spec) do |t|
    t.pattern = "spec/**/*_spec.rb"
    t.rspec_opts = "--color --format documentation"
  end
end
