// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1c6a7c50058aa5f56dd55dec2ddb1810094fc641d35ad98ce5e4f5c4e6080dc8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace Kreuzberg;

internal sealed class ApiDocSafeHandle : SafeHandle
{
    internal ApiDocSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.ApiDocFree(handle);
        return true;
    }
}

/// <summary>
/// OpenAPI documentation structure.
///
/// Defines all endpoints, request/response schemas, and examples
/// for the Kreuzberg document extraction API.
/// </summary>
public sealed class ApiDoc : IDisposable
{
    private readonly ApiDocSafeHandle _safeHandle;

    internal ApiDoc(IntPtr handle)
    {
        _safeHandle = new ApiDocSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();
}
