// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dd045debf1412184bb741e66dfec83dbd60c6802c1fa81f4ccf5dec6b3b60cec
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A single file extracted from an archive.
///
/// When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction
/// enabled, each processable file produces its own full `ExtractionResult`.
/// </summary>
public sealed class ArchiveEntry
{
    /// <summary>
    /// Archive-relative file path (e.g. "folder/document.pdf").
    /// </summary>
    [JsonPropertyName("path")]
    public string Path { get; set; } = "";

    /// <summary>
    /// Detected MIME type of the file.
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string MimeType { get; set; } = "";

    /// <summary>
    /// Full extraction result for this file.
    /// </summary>
    [JsonPropertyName("result")]
    public ExtractionResult Result { get; set; } = default!;

}
