// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6bad9fe22dcd23ffa658e0c30fcc0904cd0d4b6aacf424ea9ce088b12b6aa905
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Convenience type alias for a pooled Vec<u8>.
/// </summary>
public sealed class ByteBufferPool : IDisposable
{
    internal IntPtr Handle { get; }

    internal ByteBufferPool(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
