// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:97001a5d5c941c410dabe1e374bd50ebc7f37cd9b3690b333b990dfb55356885
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Chunk request with text and configuration.
/// </summary>
public sealed class ChunkRequest
{
    /// <summary>
    /// Text to chunk (must not be empty)
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    /// <summary>
    /// Optional chunking configuration
    /// </summary>
    [JsonPropertyName("config")]
    public string? Config { get; set; } = null;

    /// <summary>
    /// Chunker type (text, markdown, yaml, or semantic)
    /// </summary>
    [JsonPropertyName("chunker_type")]
    public string ChunkerType { get; set; } = "";


    /// <summary>
    /// Parse a <see cref="ChunkRequest"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static ChunkRequest FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ChunkRequest>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse ChunkRequest from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse ChunkRequest from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
