// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4b70d242207c936257033c50a30913e00d0d8fd7bd8b25e5ba9fae68b3d7c6b9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Common metadata fields extracted from a PDF.
/// </summary>
public sealed class CommonPdfMetadata
{
    [JsonPropertyName("title")]
    public string? Title { get; set; } = null;

    [JsonPropertyName("subject")]
    public string? Subject { get; set; } = null;

    [JsonPropertyName("authors")]
    public List<string>? Authors { get; set; } = null;

    [JsonPropertyName("keywords")]
    public List<string>? Keywords { get; set; } = null;

    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; } = null;

    [JsonPropertyName("modified_at")]
    public string? ModifiedAt { get; set; } = null;

    [JsonPropertyName("created_by")]
    public string? CreatedBy { get; set; } = null;

}
