// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:197027f14189f86d40955719c31136ef39a00eaa3f9ecc3998a85952e71d849f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// OpenWebUI "Docling" engine response format.
///
/// Returned by `POST /v1/convert/file` for docling-serve compatibility.
/// </summary>
public sealed class DoclingCompatResponse
{
    /// <summary>
    /// Converted document content
    /// </summary>
    [JsonPropertyName("document")]
    public string Document { get; set; } = "";

    /// <summary>
    /// Processing status
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = "";

}
