// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1cbc9fb12a01d39b7d5d00683ee93cd94b11fd5649f00c8fa50d5b877a13b223
#nullable enable

using System;

namespace Kreuzberg;

public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
