// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f288d203f304359059ea930a406a9a16119040bb651e111af077d918db6f609a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;

namespace Kreuzberg;

/// <summary>
/// Helper struct for validating entity/string length.
/// </summary>
public sealed class EntityValidator : IDisposable
{
    internal IntPtr Handle { get; }

    internal EntityValidator(IntPtr handle)
    {
        Handle = handle;
    }

    public void Dispose()
    {
        // Native free will be called by the runtime
    }
}
