// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a27ac5417ea739e2f171562f73de18b0ea1956a1917ec2efe423883b5f062c53
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;
namespace Kreuzberg;

internal sealed class ExtractResponseSafeHandle : SafeHandle
{
    internal ExtractResponseSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.ExtractResponseFree(handle);
        return true;
    }
}
/// <summary>/// Extraction response (list of results)./// </summary>
public sealed class ExtractResponse : IDisposable
{
    private readonly ExtractResponseSafeHandle _safeHandle;

    internal ExtractResponse(IntPtr handle)
    {
        _safeHandle = new ExtractResponseSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
