// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7d402d16ec14ce2bbcd3296675cd4e1c856f9da613ff0272505f30cd8dc2aa57
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Footnote in Djot.
/// </summary>
public sealed class Footnote
{
    /// <summary>
    /// Footnote label
    /// </summary>
    [JsonPropertyName("label")]
    public string Label { get; set; } = "";

    /// <summary>
    /// Footnote content blocks
    /// </summary>
    [JsonPropertyName("content")]
    public List<FormattedBlock> Content { get; set; } = [];

}
