// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:69c434c8158096e3ecdd1aa493c2e2f1e9eaee53a62513f5e5192a4e0648e3e7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Format-specific metadata (discriminated union).
///
/// Only one format type can exist per extraction result. This provides
/// type-safe, clean metadata without nested optionals.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "format_type")]
[JsonDerivedType(typeof(Pdf), "pdf")]
[JsonDerivedType(typeof(Docx), "docx")]
[JsonDerivedType(typeof(Excel), "excel")]
[JsonDerivedType(typeof(Email), "email")]
[JsonDerivedType(typeof(Pptx), "pptx")]
[JsonDerivedType(typeof(Archive), "archive")]
[JsonDerivedType(typeof(Image), "image")]
[JsonDerivedType(typeof(Xml), "xml")]
[JsonDerivedType(typeof(Text), "text")]
[JsonDerivedType(typeof(Html), "html")]
[JsonDerivedType(typeof(Ocr), "ocr")]
[JsonDerivedType(typeof(Csv), "csv")]
[JsonDerivedType(typeof(Bibtex), "bibtex")]
[JsonDerivedType(typeof(Citation), "citation")]
[JsonDerivedType(typeof(FictionBook), "fiction_book")]
[JsonDerivedType(typeof(Dbf), "dbf")]
[JsonDerivedType(typeof(Jats), "jats")]
[JsonDerivedType(typeof(Epub), "epub")]
[JsonDerivedType(typeof(Pst), "pst")]
[JsonDerivedType(typeof(Code), "code")]
public abstract record FormatMetadata
{
    public sealed record Pdf(
        PdfMetadata Value
    ) : FormatMetadata;

    public sealed record Docx(
        DocxMetadata Value
    ) : FormatMetadata;

    public sealed record Excel(
        ExcelMetadata Value
    ) : FormatMetadata;

    public sealed record Email(
        EmailMetadata Value
    ) : FormatMetadata;

    public sealed record Pptx(
        PptxMetadata Value
    ) : FormatMetadata;

    public sealed record Archive(
        ArchiveMetadata Value
    ) : FormatMetadata;

    public sealed record Image(
        string Value
    ) : FormatMetadata;

    public sealed record Xml(
        XmlMetadata Value
    ) : FormatMetadata;

    public sealed record Text(
        TextMetadata Value
    ) : FormatMetadata;

    public sealed record Html(
        HtmlMetadata Value
    ) : FormatMetadata;

    public sealed record Ocr(
        OcrMetadata Value
    ) : FormatMetadata;

    public sealed record Csv(
        CsvMetadata Value
    ) : FormatMetadata;

    public sealed record Bibtex(
        BibtexMetadata Value
    ) : FormatMetadata;

    public sealed record Citation(
        CitationMetadata Value
    ) : FormatMetadata;

    public sealed record FictionBook(
        FictionBookMetadata Value
    ) : FormatMetadata;

    public sealed record Dbf(
        DbfMetadata Value
    ) : FormatMetadata;

    public sealed record Jats(
        JatsMetadata Value
    ) : FormatMetadata;

    public sealed record Epub(
        EpubMetadata Value
    ) : FormatMetadata;

    public sealed record Pst(
        PstMetadata Value
    ) : FormatMetadata;

    public sealed record Code(
        string Value
    ) : FormatMetadata;

    /// <summary>Returns the Pdf data if this is a Pdf variant, otherwise null.</summary>
    public PdfMetadata? AsPdf => this is Pdf e ? e.Value : null;

    /// <summary>Returns the Docx data if this is a Docx variant, otherwise null.</summary>
    public DocxMetadata? AsDocx => this is Docx e ? e.Value : null;

    /// <summary>Returns the Excel data if this is a Excel variant, otherwise null.</summary>
    public ExcelMetadata? AsExcel => this is Excel e ? e.Value : null;

    /// <summary>Returns the Email data if this is a Email variant, otherwise null.</summary>
    public EmailMetadata? AsEmail => this is Email e ? e.Value : null;

    /// <summary>Returns the Pptx data if this is a Pptx variant, otherwise null.</summary>
    public PptxMetadata? AsPptx => this is Pptx e ? e.Value : null;

    /// <summary>Returns the Archive data if this is a Archive variant, otherwise null.</summary>
    public ArchiveMetadata? AsArchive => this is Archive e ? e.Value : null;

    /// <summary>Returns the Image data if this is a Image variant, otherwise null.</summary>
    public string? AsImage => this is Image e ? e.Value : null;

    /// <summary>Returns the Xml data if this is a Xml variant, otherwise null.</summary>
    public XmlMetadata? AsXml => this is Xml e ? e.Value : null;

    /// <summary>Returns the Text data if this is a Text variant, otherwise null.</summary>
    public TextMetadata? AsText => this is Text e ? e.Value : null;

    /// <summary>Returns the Html data if this is a Html variant, otherwise null.</summary>
    public HtmlMetadata? AsHtml => this is Html e ? e.Value : null;

    /// <summary>Returns the Ocr data if this is a Ocr variant, otherwise null.</summary>
    public OcrMetadata? AsOcr => this is Ocr e ? e.Value : null;

    /// <summary>Returns the Csv data if this is a Csv variant, otherwise null.</summary>
    public CsvMetadata? AsCsv => this is Csv e ? e.Value : null;

    /// <summary>Returns the Bibtex data if this is a Bibtex variant, otherwise null.</summary>
    public BibtexMetadata? AsBibtex => this is Bibtex e ? e.Value : null;

    /// <summary>Returns the Citation data if this is a Citation variant, otherwise null.</summary>
    public CitationMetadata? AsCitation => this is Citation e ? e.Value : null;

    /// <summary>Returns the FictionBook data if this is a FictionBook variant, otherwise null.</summary>
    public FictionBookMetadata? AsFictionBook => this is FictionBook e ? e.Value : null;

    /// <summary>Returns the Dbf data if this is a Dbf variant, otherwise null.</summary>
    public DbfMetadata? AsDbf => this is Dbf e ? e.Value : null;

    /// <summary>Returns the Jats data if this is a Jats variant, otherwise null.</summary>
    public JatsMetadata? AsJats => this is Jats e ? e.Value : null;

    /// <summary>Returns the Epub data if this is a Epub variant, otherwise null.</summary>
    public EpubMetadata? AsEpub => this is Epub e ? e.Value : null;

    /// <summary>Returns the Pst data if this is a Pst variant, otherwise null.</summary>
    public PstMetadata? AsPst => this is Pst e ? e.Value : null;

    /// <summary>Returns the Code data if this is a Code variant, otherwise null.</summary>
    public string? AsCode => this is Code e ? e.Value : null;

}
