// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4e1991e6c43388e8b679b19b59980cbc596680ca7a4f3d98a0a4f39fd81b125a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A single heading in the hierarchy.
/// </summary>
public sealed class HeadingLevel
{
    /// <summary>
    /// Heading depth (1 = h1, 2 = h2, etc.)
    /// </summary>
    [JsonPropertyName("level")]
    public byte Level { get; set; } = 0;

    /// <summary>
    /// The text content of the heading.
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";


    /// <summary>
    /// Parse a <see cref="HeadingLevel"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static HeadingLevel FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<HeadingLevel>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse HeadingLevel from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse HeadingLevel from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
