// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a8bff93d45ad588a947bb7e280e6f456d950d35007b8116caeb2712e0210c2c6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A text block with hierarchy level assignment.
///
/// Represents a block of text with semantic heading information extracted from
/// font size clustering and hierarchical analysis.
/// </summary>
public sealed class HierarchicalBlock
{
    /// <summary>
    /// The text content of this block
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    /// <summary>
    /// The font size of the text in this block
    /// </summary>
    [JsonPropertyName("font_size")]
    public float FontSize { get; set; } = 0.0;

    /// <summary>
    /// The hierarchy level of this block (H1-H6 or Body)
    ///
    /// Levels correspond to HTML heading tags:
    /// - "h1": Top-level heading
    /// - "h2": Secondary heading
    /// - "h3": Tertiary heading
    /// - "h4": Quaternary heading
    /// - "h5": Quinary heading
    /// - "h6": Senary heading
    /// - "body": Body text (no heading level)
    /// </summary>
    [JsonPropertyName("level")]
    public string Level { get; set; } = "";

    /// <summary>
    /// Bounding box information for the block
    ///
    /// Contains coordinates as (left, top, right, bottom) in PDF units.
    /// </summary>
    [JsonPropertyName("bbox")]
    public List<float>? Bbox { get; set; } = null;

}
