// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ae8ed905669367a9fef5513df6683082d7f01599a0568520fde5d0c668f63b5a
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
