// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:623e86f2898231f19eb82a7ceca495a212ce62c3f75c394887fe271814f4926b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class OcrCacheStats
{
    [JsonPropertyName("total_files")]
    public ulong TotalFiles { get; set; } = 0;

    [JsonPropertyName("total_size_mb")]
    public double TotalSizeMb { get; set; } = 0.0;

}
