// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:beb0fd5b540004e1e9b5462b3710ae8ce4fb032320a1fe04e00ea377249fbae2
#nullable enable

using System;

namespace Kreuzberg;

public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
