// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4446b28f8755fe39e37e169f5ae796ecaaaeb583a32975620bcb38af07b19e9d
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
