// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:82b9441592d47dacf8d1404f4339e808ad2dd95083947cebe1f05785c6c9bcf9
#nullable enable

using System;

namespace Kreuzberg;

public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
