// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:686da8a6b309272d04f903a3faa6554d8bf35b90dc8dff0efd6952f33414e99a
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public enum ReductionLevel
{[JsonPropertyName("off")]
    Off,[JsonPropertyName("light")]
    Light,[JsonPropertyName("moderate")]
    Moderate,[JsonPropertyName("aggressive")]
    Aggressive,[JsonPropertyName("maximum")]
    Maximum,}
