// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:edd424f30592bb2685ca140ecd49e59dcc77292c1fd00ee4318f3cb3c2393b31
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Semantic kind of a relationship between document elements.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum RelationshipKind
{    /// <summary>
     /// Footnote marker -> footnote definition.
     /// </summary>
    [JsonPropertyName("footnote_reference")]
    FootnoteReference,    /// <summary>
                          /// Citation marker -> bibliography entry.
                          /// </summary>
    [JsonPropertyName("citation_reference")]
    CitationReference,    /// <summary>
                          /// Internal anchor link (`#id`) -> target heading/element.
                          /// </summary>
    [JsonPropertyName("internal_link")]
    InternalLink,    /// <summary>
                     /// Caption paragraph -> figure/table it describes.
                     /// </summary>
    [JsonPropertyName("caption")]
    Caption,    /// <summary>
                /// Label -> labeled element (HTML `<label for>`, LaTeX `\label{}`).
                /// </summary>
    [JsonPropertyName("label")]
    Label,    /// <summary>
              /// TOC entry -> target section.
              /// </summary>
    [JsonPropertyName("toc_entry")]
    TocEntry,    /// <summary>
                 /// Cross-reference (LaTeX `\ref{}`, DOCX cross-reference field).
                 /// </summary>
    [JsonPropertyName("cross_reference")]
    CrossReference,
}
