// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a044af6e6e78ca60df2a9a8031add4fb61388812bd8ac57ebac7c43e1abbe98c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Fully resolved (flattened) style after walking the inheritance chain.
/// </summary>
public sealed class ResolvedStyle
{
    [JsonPropertyName("paragraph_properties")]
    public string ParagraphProperties { get; set; } = "";

    [JsonPropertyName("run_properties")]
    public string RunProperties { get; set; } = "";


    /// <summary>
    /// Parse a <see cref="ResolvedStyle"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static ResolvedStyle FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ResolvedStyle>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse ResolvedStyle from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse ResolvedStyle from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
