// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d602d2a6a82e6af1719aedc1f3c459abdf3471b5f6ff0709c23609bd7e3faf27
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
