// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0b6d09670104ec68b316597877d634732e8e9d436d360a3dc0dfeb37f44e9084
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
