// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:85be9a07fffb3151dcec01e29dfc1433b97db8710e1e871c77a1e46d629bcb1c
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
