// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7b4b837627077d8ba0cc7c3d2eed8c18b87c44ebf08349a0e3b194747ca7064f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// YAKE-specific parameters.
/// </summary>
public sealed class YakeParams
{
    /// <summary>
    /// Window size for co-occurrence analysis (default: 2).
    ///
    /// Controls the context window for computing co-occurrence statistics.
    /// </summary>
    [JsonPropertyName("window_size")]
    public ulong WindowSize { get; set; } = 2;


    /// <summary>
    /// Parse a <see cref="YakeParams"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static YakeParams FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<YakeParams>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse YakeParams from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse YakeParams from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
