// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b5d9f87099b4e27ff08d6b88ce1f05518ffcaceae9326654f3d325df4a4d2f90
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [wasm()],
  test: {
    include: ["tests/**/*.test.ts"],
    setupFiles: ["./setup.ts"],
  },
});
