# Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
# To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang r
#
# Tests for xml fixtures.
# nolint start

test_that("xml_plant_catalog", {
  result <- run_fixture(
    "xml_plant_catalog",
    "xml/plant_catalog.xml",
    NULL,
    requirements = character(0),
    notes = NULL,
    skip_if_missing = TRUE
  )
      assert_expected_mime(result, c("application/xml"))
      assert_min_content_length(result, 100L)
})
# nolint end
