// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:55706ed76da2e20f9110d399607c90d3a30eb40cd1fcd7476225ddd306cd2cb5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Chunk request with text and configuration.
 */
public record ChunkRequest(
    /** Text to chunk (must not be empty) */
    String text,
    /** Optional chunking configuration */
    Optional<String> config,
    /** Chunker type (text, markdown, yaml, or semantic) */
    @JsonProperty("chunker_type") String chunkerType
) {
}
