// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3b7697f17a0824098ba7783be5dd82ebe10c69e4308b2e91365b38d8879ec906
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Byte offset boundary for a page.
 *
 * Tracks where a specific page's content starts and ends in the main content string,
 * enabling mapping from byte positions to page numbers. Offsets are guaranteed to be
 * at valid UTF-8 character boundaries when using standard String methods (push_str, push, etc.).
 */
public record PageBoundary(
    /** Byte offset where this page starts in the content string (UTF-8 valid boundary, inclusive) */
    @JsonProperty("byte_start") long byteStart,
    /** Byte offset where this page ends in the content string (UTF-8 valid boundary, exclusive) */
    @JsonProperty("byte_end") long byteEnd,
    /** Page number (1-indexed) */
    @JsonProperty("page_number") long pageNumber
) {
}
