// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:319abcf9f9960542a33c3ed238a8f28195821b56139013b0544b3c503ed5dcc2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Kreuzberg
import RustBridge

/// E2e tests for category: registry_operations.
final class RegistryOperationsTests: XCTestCase {
    func testExtensionsDocx() throws {
        // Get file extensions for DOCX MIME type
        let result = try RustBridge.getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    func testExtensionsHtml() throws {
        // Get file extensions for HTML MIME type
        let result = try RustBridge.getExtensionsForMime("text/html")
    }

    func testExtensionsPdf() throws {
        // Get file extensions for PDF MIME type
        let result = try RustBridge.getExtensionsForMime("application/pdf")
        XCTAssertTrue(result.contains("pdf"), "expected to contain: \("pdf")")
    }

}
