# This file is auto-generated by alef. DO NOT EDIT.
# E2e tests for category: xml

test_that("xml_plant_catalog: XML plant catalog to validate streaming XML extraction.", {
  result <- extract_file(path = "xml/plant_catalog.xml")
  expect_equal(trimws(result$mime_type), "application/xml")
  expect_true(nchar(result$content) >= 100)
})
