# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c6aeafbc1e6c805af1f020b461f08ca03ef3b38d19b5112bba01036a6efd8f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: renderer_management

test_that("renderers_clear: Clear all renderers and verify list is empty", {
  invisible(clear_renderers())
  expect_true(TRUE)
})

test_that("renderers_list: List all registered renderers", {
  result <- list_renderers()
  expect_true(TRUE)
})
