# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0a781a1d58fa16b65cfe45eed0e9c96f1a1e99b238a5851752bb4f5905ed2848
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: batch

test_that("batch_bytes_invalid_mime: batch_extract_bytes_sync invalid MIME", {
  result <- batch_extract_bytes_sync(items = c(list("content" = c(72, 101, 108, 108, 111), "mime_type" = "application/x-nonexistent")))
})

test_that("batch_extract_bytes_happy: batch_extract_bytes: happy path with mixed inputs", {
  result <- batch_extract_bytes(items = c(list("content" = "hello, world!", "mime_type" = "text/plain"), list("content" = "<html><body>Test</body></html>", "mime_type" = "text/html")))
  expect_true(length(result$results) >= 1)
})

test_that("batch_extract_bytes_mixed_format: batch_extract_bytes: handles unsupported MIME gracefully", {
  result <- batch_extract_bytes(items = c(list("content" = "pdf placeholder", "mime_type" = "application/x-unknown")))
})

test_that("batch_extract_bytes_size_cap: batch_extract_bytes: respects security limits", {
  expect_error(batch_extract_bytes(items = c(list("content" = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "mime_type" = "text/plain")), config = list("security_limits" = list("max_extraction_size" = 50))))
})

test_that("batch_extract_bytes_sync_empty_list: batch_extract_bytes_sync: empty batch", {
  result <- batch_extract_bytes_sync(items = c())
  expect_equal(length(result$results), 0)
})

test_that("batch_extract_bytes_sync_invalid_mime: batch_extract_bytes_sync: unsupported MIME", {
  result <- batch_extract_bytes_sync(items = c(list("content" = "data", "mime_type" = "application/x-unknown")))
})

test_that("batch_file_async_basic: Extract text from multiple files asynchronously", {
  result <- batch_extract_files(paths = c(list("path" = "pdf/fake_memo.pdf"), list("path" = "text/fake_text.txt")))
})

test_that("batch_file_async_not_found: batch_extract_file async nonexistent", {
  result <- batch_extract_files(paths = c(list("path" = "/nonexistent/a.pdf")))
})

test_that("batch_file_not_found: batch_extract_file_sync nonexistent", {
  result <- batch_extract_files_sync(paths = c(list("path" = "/nonexistent/a.pdf"), list("path" = "/nonexistent/b.txt")))
})

test_that("batch_file_partial: batch_extract_file_sync mixed", {
  result <- batch_extract_files_sync(paths = c(list("path" = "text/plain.txt"), list("path" = "/nonexistent/missing.pdf")))
})

test_that("batch_file_sync_basic: Extract text from multiple files synchronously", {
  result <- batch_extract_files_sync(paths = c(list("path" = "pdf/fake_memo.pdf"), list("path" = "text/fake_text.txt")))
})
