# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d1563cceec7ed8b2af641056d98d721b937933094ddef85de6da5f6d9d06c416
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: format_specific

test_that("format_docx_standalone: Standalone DOCX extraction using extract_bytes_sync", {
  result <- extract_bytes_sync(data = "docx/fake.docx", mime_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
  expect_true(nchar(result$content) >= 20)
})

test_that("format_pdf_text: Standalone PDF text extraction using extract_bytes_sync", {
  result <- extract_bytes_sync(data = "pdf/fake_memo.pdf", mime_type = "application/pdf")
  expect_true(nchar(result$content) >= 50)
  expect_true(any(sapply(c("Mallori", "May"), function(v) grepl(v, result$content, fixed = TRUE))))
})

test_that("format_pptx: PPTX presentation extraction using extract_bytes_sync", {
  result <- extract_bytes_sync(mime_type = "application/vnd.openxmlformats-officedocument.presentationml.presentation")
})

test_that("format_xlsx: XLSX spreadsheet extraction using extract_bytes_sync", {
  result <- extract_bytes_sync(mime_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
})
