// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cfa2362093a01082884e7de6ec37b2a44223d0f570d9bf8ded565de0bbf10094
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: registry

test "list_document_extractors" {
    // List document extractors
    _ = try kreuzberg.list_document_extractors();
}

test "list_embedding_backends" {
    // List embedding backends
    _ = try kreuzberg.list_embedding_backends();
}

test "list_ocr_backends" {
    // List OCR backends
    _ = try kreuzberg.list_ocr_backends();
}

test "list_post_processors" {
    // List post-processors
    _ = try kreuzberg.list_post_processors();
}

test "list_renderers" {
    // List renderers
    _ = try kreuzberg.list_renderers();
}

test "list_validators" {
    // List validators
    _ = try kreuzberg.list_validators();
}
