name = "kreuzberg"
version = "5.0.0-rc.1"
description = "High-performance document intelligence library"
licences = ["MIT"]
target = "erlang"

[dependencies]
gleam_stdlib = ">= 5.0.0-rc.1 and < 5.0.0-rc.1"

[dev-dependencies]
gleeunit = ">= 5.0.0-rc.1 and < 5.0.0-rc.1"
