# This file is auto-generated by alef. DO NOT EDIT.
"""E2e tests for category: render."""

from kreuzberg import ExtractionConfig, extract_file_sync, render_page


def test_render_custom_dpi() -> None:
    """Render PDF page with custom DPI."""
    path = "pdf/tiny.pdf"
    page = 0
    result = render_page(path=path, page=page)
    assert result.is_png is True
    assert result.byte_length >= 50


def test_render_high_dpi() -> None:
    """Render PDF page with high DPI setting (300 DPI)."""
    path = "pdf/fake_memo.pdf"
    page = 0
    config = ExtractionConfig(dpi=300)
    _ = render_page(path=path, page=page, config=config)


def test_render_iterator() -> None:
    """Iterate all PDF pages as PNG images."""
    path = "pdf/tiny.pdf"
    page = 0
    result = render_page(path=path, page=page)
    assert result.is_png is True
    assert result.page_count >= 1


def test_render_multi_page() -> None:
    """Render a page from a multi-page PDF document."""
    path = "pdf/a_brief_introduction_to_neural_networks_neuronalenetze_en_zeta2_2col_dkrieselcom.pdf"
    page = 0
    result = render_page(path=path, page=page)
    assert len(result.result) >= 1000


def test_render_output_djot() -> None:
    """Extract PDF with Djot output format."""
    path = "pdf/fake_memo.pdf"
    config = ExtractionConfig(output_format="djot")
    result = extract_file_sync(path=path, config=config)
    assert result.output_format.strip() == "djot"
    assert len(result.content) >= 10


def test_render_output_html() -> None:
    """Extract PDF with HTML output format."""
    path = "pdf/fake_memo.pdf"
    config = ExtractionConfig(output_format="html")
    result = extract_file_sync(path=path, config=config)
    assert result.output_format.strip() == "html"
    assert result.content is not None
    assert any(v in result.content for v in ["<", ">", "</"])


def test_render_output_markdown() -> None:
    """Extract PDF with Markdown output format."""
    path = "pdf/fake_memo.pdf"
    config = ExtractionConfig(output_format="markdown")
    result = extract_file_sync(path=path, config=config)
    assert result.output_format.strip() == "markdown"
    assert result.content is not None
    assert any(v in result.content for v in ["#", "**", "*"])


def test_render_output_plain() -> None:
    """Extract PDF with plain text output format."""
    path = "pdf/fake_memo.pdf"
    config = ExtractionConfig(output_format="plain")
    result = extract_file_sync(path=path, config=config)
    assert result.output_format.strip() == "plain"
    assert len(result.content) >= 50


def test_render_single_page() -> None:
    """Render a single PDF page to PNG."""
    path = "pdf/tiny.pdf"
    page = 0
    result = render_page(path=path, page=page)
    assert result.is_png is True
    assert result.byte_length >= 100
