# This file is auto-generated by alef — DO NOT EDIT.
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

"""E2e tests for category: pdf."""

from pathlib import Path
import pytest  # noqa: F401
from kreuzberg import render_pdf_page_to_png


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = (
        " ".join(str(value) for value in raw_items)
        if isinstance(raw_items, list)
        else ""
    )
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


def test_render_pdf_page_first() -> None:
    """render_pdf_page_to_png: first page."""
    pdf_bytes = Path("pdf/fake_memo.pdf").read_bytes()
    page_index = 0

    result = render_pdf_page_to_png(pdf_bytes, page_index)
    assert len(result) >= 100  # noqa: S101


def test_render_pdf_page_out_of_range() -> None:
    """render_pdf_page_to_png: page out of range."""
    with pytest.raises(Exception):  # noqa: B017
        pdf_bytes = Path("pdf/fake_memo.pdf").read_bytes()
        page_index = 999
        render_pdf_page_to_png(pdf_bytes, page_index)
