# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:12668705b903380718b5557043a6b2d3b04e97bc072734b9a433ca954feba247
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: email."""

import pytest  # noqa: F401
from kreuzberg import extract_file


@pytest.mark.asyncio
async def test_email_eml_html_body() -> None:
    """EML with HTML body content."""
    path = "email/html_only.eml"
    result = await extract_file(path=path)
    assert result.mime_type.strip() == "message/rfc822"  # noqa: S101
    assert len(result.content) >= 10  # noqa: S101


@pytest.mark.asyncio
async def test_email_eml_multipart() -> None:
    """EML with multipart MIME content."""
    path = "email/html_email_multipart.eml"
    result = await extract_file(path=path)
    assert result.mime_type.strip() == "message/rfc822"  # noqa: S101
    assert len(result.content) >= 10  # noqa: S101


@pytest.mark.asyncio
async def test_email_eml_utf16() -> None:
    """UTF-16 encoded EML file with BOM."""
    path = "vendored/unstructured/eml/fake-email-utf-16.eml"
    result = await extract_file(path=path)
    assert result.mime_type.strip() == "message/rfc822"  # noqa: S101
    assert len(result.content) >= 50  # noqa: S101
    assert any(v in result.content for v in ["Test Email", "Roses are red"])  # noqa: S101


@pytest.mark.asyncio
async def test_email_msg_basic() -> None:
    """Outlook MSG file extraction."""
    path = "email/fake_email.msg"
    result = await extract_file(path=path)
    assert result.mime_type.strip() == "application/vnd.ms-outlook"  # noqa: S101
    assert len(result.content) >= 10  # noqa: S101


@pytest.mark.asyncio
async def test_email_pst_empty() -> None:
    """Empty Outlook PST archive with no messages."""
    path = "email/empty.pst"
    result = await extract_file(path=path)
    assert result.mime_type.strip() == "application/vnd.ms-outlook-pst"  # noqa: S101


@pytest.mark.asyncio
async def test_email_sample_eml() -> None:
    """Sample EML email file to verify email parsing."""
    path = "email/sample_email.eml"
    result = await extract_file(path=path)
    assert result.mime_type.strip() == "message/rfc822"  # noqa: S101
    assert len(result.content) >= 20  # noqa: S101
