// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c2048c35d4bb2989379af5b35cbb4504802936bd1d00c060cc6e13b9093c6538
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import dev.kreuzberg.ExtractionConfig;

/** E2e tests for category: document. */
class DocumentTest {

    private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new Jdk8Module());
    @Test
    void testDocMetadataDocx() throws Exception {
        // Extract DOCX metadata
        var result = Kreuzberg.extractFileSync("vendored/markitdown/test.docx");
        assertFalse(result.metadata().isEmpty(), "expected non-empty value");
    }

    @Test
    void testDocMetadataPdf() throws Exception {
        // Extract PDF metadata
        var result = Kreuzberg.extractFileSync("pdf/fake_memo.pdf");
        assertFalse(result.metadata().isEmpty(), "expected non-empty value");
    }

    @Test
    void testDocStructureDocx() throws Exception {
        // Extract DOCX document structure with include_document_structure config
        var result = Kreuzberg.extractFileSync("vendored/markitdown/test.docx", config);
        assertFalse(result.documentStructure().isEmpty(), "expected non-empty value");
    }

    @Test
    void testDocStructureHtml() throws Exception {
        // Extract HTML document structure with include_document_structure config
        var result = Kreuzberg.extractFileSync("html/html.html", config);
        assertFalse(result.documentStructure().isEmpty(), "expected non-empty value");
    }

    @Test
    void testDocStructurePdf() throws Exception {
        // Extract PDF document structure with include_document_structure config
        var result = Kreuzberg.extractFileSync("pdf/fake_memo.pdf", config);
        assertFalse(result.documentStructure().isEmpty(), "expected non-empty value");
    }

}
