// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6a0f01585262b70b46ede924bf4eabe3ddf2d69ce82c57f27baa6e2907027e76
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;import dev.kreuzberg.Kreuzberg;import dev.kreuzberg.ExtractionConfig;import java.util.Optional;
/** E2e tests for category: error. */
class ErrorTest {

    @Test
    void testErrorEmptyBytes() throws Exception {
        // Graceful handling of empty bytes (should not error)
        var config = ExtractionConfig.builder().build();

        var result = Kreuzberg.extractBytesSync("text/empty.txt".getBytes(), "text/plain", config);

    }


    @Test
    void testErrorEmptyMime() throws Exception {
        // Error when extracting with empty MIME type
        var config = ExtractionConfig.builder().build();

        assertThrows(Exception.class, () -> Kreuzberg.extractBytesSync("text/plain.txt".getBytes(), "", config));
    }


    @Test
    void testErrorExtractBytesConflictingOcr() throws Exception {
        // extract_bytes force+disable OCR
        var config = ExtractionConfig.builder().withDisableOcr(true).withForceOcr(true).build();

        assertThrows(Exception.class, () -> Kreuzberg.extractBytesSync("text/fake_text.txt".getBytes(), "text/plain", config));
    }


    @Test
    void testErrorInvalidMimeFormat() throws Exception {
        // Error when extracting with invalid MIME type format
        var config = ExtractionConfig.builder().build();

        assertThrows(Exception.class, () -> Kreuzberg.extractBytesSync("text/plain.txt".getBytes(), "not-a-mime", config));
    }


    @Test
    void testErrorUnsupportedMime() throws Exception {
        // Error when extracting with unsupported MIME type
        var config = ExtractionConfig.builder().build();

        assertThrows(Exception.class, () -> Kreuzberg.extractBytesSync("text/plain.txt".getBytes(), "application/x-nonexistent", config));
    }

}
