// This file is auto-generated by alef. DO NOT EDIT.
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: post_processor_management. */
class PostProcessorManagementTest {
    @Test
    void testPostProcessorsClear() throws Exception {
        // Clear all post-processors and verify list is empty
        var result = Kreuzberg.extractFile("");
    }

    @Test
    void testPostProcessorsList() throws Exception {
        // List all registered post-processors
        var result = Kreuzberg.extractFile("");
    }

}
