// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9ddec1ef278de78f734c3cb130426c0e5704c0ec332ec71c079ab5509eaa323d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;

/** E2e tests for category: text_processing. */
class TextProcessingTest {
    @Test
    void testTextCleanExtracted() throws Exception {
        // Extract and clean text content from document
        var result = Kreuzberg.extractFileSync("json/simple.json");
        assertTrue(result.content().length() >= 5, "expected length >= 5");
    }

    @Test
    void testTextNormalizeWhitespace() throws Exception {
        // Extract text with whitespace normalization (no consecutive spaces)
        var result = Kreuzberg.extractFileSync("pdf/fake_memo.pdf");
        assertFalse(result.content().contains("  "), "expected NOT to contain: " + "  ");
    }

}
