// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:02037ef7dd10ad836137160e815a26bfec8d2e85f19e5f95991d7246912aca58
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: validator_management. */
class ValidatorManagementTest {

    @Test
    void testValidatorsClear() throws Exception {
        // Clear all validators and verify list is empty
        Kreuzberg.clearValidators();

    }


    @Test
    void testValidatorsList() throws Exception {
        // List all registered validators
        var result = Kreuzberg.listValidators();

    }

}
