# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a153386788afe29710bfbc2d1d81f1ef25e4ccc8fe385113dacc6fa3feca5d4f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = "5.0.0.pre.rc.3"
end
