# kreuzberg-ffi version compatibility check

# AUTO-UPDATED by sync-versions — do not edit manually
set(PACKAGE_VERSION "4.3.8")

# Parse into components
string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)" _KREUZBERG_VERSION_MATCH "${PACKAGE_VERSION}")
set(PACKAGE_VERSION_MAJOR "${CMAKE_MATCH_1}")
set(PACKAGE_VERSION_MINOR "${CMAKE_MATCH_2}")
set(PACKAGE_VERSION_PATCH "${CMAKE_MATCH_3}")

if(PACKAGE_FIND_VERSION_MAJOR EQUAL PACKAGE_VERSION_MAJOR)
  if(PACKAGE_FIND_VERSION VERSION_LESS_EQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
      set(PACKAGE_VERSION_EXACT TRUE)
    endif()
  else()
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  endif()
elseif(NOT DEFINED PACKAGE_FIND_VERSION_MAJOR)
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
else()
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()
