// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:91e50ac9c3577123ab4a52757e996082c24fa2bf2c898fe7b9e59a9537fcfa6d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;

/**
 * Archive (ZIP/TAR/7Z) metadata.
 *
 * Extracted from compressed archive files containing file lists and size
 * information.
 */
public class ArchiveMetadataBuilder {

	private String format = "";
	private long fileCount = 0;
	private List<String> fileList = List.of();
	private long totalSize = 0;
	private Optional<Long> compressedSize = Optional.empty();

	/** Sets the format field. */
	public ArchiveMetadataBuilder withFormat(final String value) {
		this.format = value;
		return this;
	}

	/** Sets the fileCount field. */
	public ArchiveMetadataBuilder withFileCount(final long value) {
		this.fileCount = value;
		return this;
	}

	/** Sets the fileList field. */
	public ArchiveMetadataBuilder withFileList(final List<String> value) {
		this.fileList = value;
		return this;
	}

	/** Sets the totalSize field. */
	public ArchiveMetadataBuilder withTotalSize(final long value) {
		this.totalSize = value;
		return this;
	}

	/** Sets the compressedSize field. */
	public ArchiveMetadataBuilder withCompressedSize(final Optional<Long> value) {
		this.compressedSize = value;
		return this;
	}

	/** Builds the ArchiveMetadata instance. */
	public ArchiveMetadata build() {
		return new ArchiveMetadata(format, fileCount, fileList, totalSize, compressedSize);
	}
}
