// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:23a7d53fc500c6be52b569689fb0659c3e05d9fd2997a04e68a1d67559498f6d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record BBox(float x1, float y1, float x2, float y2) {
}}
