// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4a8b97f89a04600a14751b148c982914d90237181e803f18f1e3ec716511753d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Convenience type alias for a pooled Vec&lt;u8&gt;.
 */
@SuppressWarnings("checkstyle:LineLength")
public class ByteBufferPool implements AutoCloseable {
    private final MemorySegment handle;

    ByteBufferPool(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_BYTE_BUFFER_POOL_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free ByteBufferPool: " + e.getMessage(), e);
            }
        }
    }
}
