// DO NOT EDIT - auto-generated by alef
// alef:hash:4de2d27aa554019f110ca8dfb6810f301dd0c42a6a85d118073be4482bd5cf26
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
