// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dd041a08840544a73d0e45d8a60bad4485a971ce1002fd8407f7e0845dc3689d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Request parameters for cache warm (model download).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record CacheWarmParams(
        /** Download all embedding model presets */
        @JsonProperty("all_embeddings") boolean allEmbeddings,
        /** Specific embedding preset name to download (e.g. "balanced", "speed", "quality") */
        @Nullable @JsonProperty("embedding_model") String embeddingModel) {
}
