// DO NOT EDIT - auto-generated by alef
// alef:hash:7a81ce7256ca04d90f8b1380fd4e7b8d9bb418b32981b1d9607af1e30b6144b4
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
