// DO NOT EDIT - auto-generated by alef
// alef:hash:41803f8942b44c8ad971679b7524941c989b88b2f6c59a79c550ed6234550c64
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
