// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f60bba941753d002d88c55bf7c6c3c38165f80d752adf3f1f14293065562a6c5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jetbrains.annotations.Nullable;

/**
 * Request parameters for cache warm (model download).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record CacheWarmParams(
        /** Download all embedding model presets */
        @JsonProperty("all_embeddings") boolean allEmbeddings,
        /** Specific embedding preset name to download (e.g. "balanced", "speed", "quality") */
        @Nullable @JsonProperty("embedding_model") String embeddingModel) {
}
