// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9cc84e095423e7a643b10cb16a63cad38057627bbfc23aa32e8be4ec3bec1458
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

@JsonPOJOBuilder(withPrefix = "with")
public class CharShapeBuilder {

    private boolean bold = false;
    private boolean italic = false;
    private boolean underline = false;

    /** Sets the bold field. */
    public CharShapeBuilder withBold(final boolean value) {
        this.bold = value;
        return this;
    }

    /** Sets the italic field. */
    public CharShapeBuilder withItalic(final boolean value) {
        this.italic = value;
        return this;
    }

    /** Sets the underline field. */
    public CharShapeBuilder withUnderline(final boolean value) {
        this.underline = value;
        return this;
    }

    /** Builds the CharShape instance. */
    public CharShape build() {
        return new CharShape(bold, italic, underline);
    }
}
