// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:feee465a43c2f7074f39455f87455b44df943fc86259ca84ea31be713bd8112d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Chunk request with text and configuration.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ChunkRequest(
    String text,
    @Nullable String config,
    @JsonProperty("chunker_type") String chunkerType
) {

    /**
     * Parse a {@code ChunkRequest} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static ChunkRequest fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ChunkRequest.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse ChunkRequest from JSON: " + e.getMessage(), e);
        }
    }
}
