// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:16df1b4b0d4c01a2e4b73c149455d0d2777a676979dbc2ca9cf3a4b60ce98879
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;

/**
 * JATS contributor with role.
 */
public record ContributorRole(String name, Optional<String> role) {
}
