// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:60c5cec14229478a60e95dd5e4baf4c2149557b2fac702b1f34655fcbd401086
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * JATS contributor with role.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ContributorRole(String name, @Nullable String role) {

    /**
     * Parse a {@code ContributorRole} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static ContributorRole fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ContributorRole.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse ContributorRole from JSON: " + e.getMessage(), e);
        }
    }
}
