// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71f225803b430526b0467bd2d0942d7d7b491e9a6a4bdc2e65f1efde17e25fda
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * dBASE field information.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DbfFieldInfo(String name, @JsonProperty("field_type") String fieldType) {
}
