// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:88e6f613f33797365dffa0106f3292d2f5029fffa20a9062f272b42dbd797fec
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * dBASE (DBF) file metadata.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class DbfMetadataBuilder {

    private long recordCount = 0;
    private long fieldCount = 0;
    private List<DbfFieldInfo> fields = List.of();

    /** Sets the recordCount field. */
    public DbfMetadataBuilder withRecordCount(final long value) {
        this.recordCount = value;
        return this;
    }

    /** Sets the fieldCount field. */
    public DbfMetadataBuilder withFieldCount(final long value) {
        this.fieldCount = value;
        return this;
    }

    /** Sets the fields field. */
    public DbfMetadataBuilder withFields(final List<DbfFieldInfo> value) {
        this.fields = value;
        return this;
    }

    /** Builds the DbfMetadata instance. */
    public DbfMetadata build() {
        return new DbfMetadata(recordCount, fieldCount, fields);
    }
}
