// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f65eb96ed4a157c2c3b95f0205c02ac85d897603a8694da1a037f75551bf51b4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Page-level detection result containing all detections and page metadata.
 */
public record DetectionResult(@JsonProperty("page_width") int pageWidth, @JsonProperty("page_height") int pageHeight,
		List<LayoutDetection> detections) {
}
