// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:25a8e975be5b22f35d95d581d99120e91ba4c263a8acd5121dde8d9b8d7e74d6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Image element in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DjotImage(
    /** Image source URL or path */
    String src,
    /** Alternative text */
    String alt,
    /** Optional title */
    @Nullable String title,
    /** Element attributes */
    @Nullable String attributes
) {
}
