// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c5fab66f6baf43bab5ff9017a50290a5a18f1c277e07cea15821ab004a8fc22b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A resolved relationship between two nodes in the document tree.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DocumentRelationship(int source, int target, RelationshipKind kind) {
}
