// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:59852dd41a9d8003a5d564642a0474c02ab9efff0b29e84a2beb63b15186ac05
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A single node in the document tree.
 *
 * Each node has deterministic {@code id}, typed {@code content}, optional {@code parent}/{@code children}
 * for tree structure, and metadata like page number, bounding box, and content layer.
 */
public record DocumentNode(
    /** Deterministic identifier (hash of content + position). */
    String id,
    /** Node content — tagged enum, type-specific data only. */
    NodeContent content,
    /** Parent node index ({@code None} = root-level node). */
    Optional<Integer> parent,
    /** Child node indices in reading order. */
    List<Integer> children,
    /** Content layer classification. */
    @JsonProperty("content_layer") ContentLayer contentLayer,
    /** Page number where this node starts (1-indexed). */
    Optional<Integer> page,
    /** Page number where this node ends (for multi-page tables/sections). */
    @JsonProperty("page_end") Optional<Integer> pageEnd,
    /** Bounding box in document coordinates. */
    Optional<String> bbox,
    /** Inline annotations (formatting, links) on this node's text content. */
    List<TextAnnotation> annotations,
    /** Format-specific key-value attributes. */
    Optional<Map<String, String>> attributes
) {
}
