// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:07ca13deeb24f102d13e2bf1980ff0431a749fe7e9125a08db080217ea26c465
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Word document metadata.
 *
 * Extracted from DOCX files using shared Office Open XML metadata extraction. Integrates with {@code office_metadata}
 * module for core/app/custom properties.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DocxMetadataBuilder.class)
public record DocxMetadata(
        /** Core properties from docProps/core.xml (Dublin Core metadata) */
        @Nullable @JsonProperty("core_properties") String coreProperties,
        /** Application properties from docProps/app.xml (Word-specific statistics) */
        @Nullable @JsonProperty("app_properties") String appProperties,
        /** Custom properties from docProps/custom.xml (user-defined properties) */
        @Nullable @JsonProperty("custom_properties") Map<String, Object> customProperties) {
    public static DocxMetadataBuilder builder() {
        return new DocxMetadataBuilder();
    }
}
