// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0efc171ff023d988496dec50fa461a2acab0cca4325c59bafcac3f82dc5da0c0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for email extraction.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmailConfigBuilder.class)
public record EmailConfig(@Nullable @JsonProperty("msg_fallback_codepage") Integer msgFallbackCodepage) {
    public static EmailConfigBuilder builder() {
        return new EmailConfigBuilder();
    }
}
