// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bb7f32751f7228eff814c242083d0c117ee8e64f2c40c2f3d6d5fca66598c239
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Embedding model types supported by Kreuzberg.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({@JsonSubTypes.Type(value = EmbeddingModelType.Preset.class, name = "preset"),
        @JsonSubTypes.Type(value = EmbeddingModelType.Custom.class, name = "custom"),
        @JsonSubTypes.Type(value = EmbeddingModelType.Llm.class, name = "llm"),
        @JsonSubTypes.Type(value = EmbeddingModelType.Plugin.class, name = "plugin")})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface EmbeddingModelType {

    /** Use a preset model configuration (recommended) */
    record Preset(@JsonProperty("name") String name) implements EmbeddingModelType {
    }

    /** Use a custom ONNX model from HuggingFace */
    record Custom(@JsonProperty("model_id") String modelId,
            @JsonProperty("dimensions") long dimensions) implements EmbeddingModelType {
    }

    /** Provider-hosted embedding model via liter-llm. */
    record Llm(@JsonProperty("llm") LlmConfig llm) implements EmbeddingModelType {
    }

    /** In-process embedding backend registered via the plugin system. */
    record Plugin(@JsonProperty("name") String name) implements EmbeddingModelType {
    }
}
