// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f21d2f75e452151626ac950af0c03cac1ec8b44222def1d49820150554fd34ad
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Preset configurations for common RAG use cases.
 *
 * Each preset combines chunk size, overlap, and embedding model
 * to provide an optimized configuration for specific scenarios.
 *
 * All string fields are owned {@code String} for FFI compatibility — instances
 * are safe to clone and pass across language boundaries.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record EmbeddingPreset(
}}
