// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71f0ea48b2a18e5ea8763a7b6aaefda0f041664e0d0b1c89357c938b7ba6f9da
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Embedding response containing generated embeddings.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record EmbedResponse(
    @JsonInclude(JsonInclude.Include.NON_NULL) List<List<Float>> embeddings,
    String model,
    long dimensions,
    long count
) {
}
