// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:77645ef1f8055c612266cb9550496be7d3131606b49f2a7b62962c036c1d5001
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Error metadata (for batch operations).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ErrorMetadata(@JsonProperty("error_type") String errorType, String message) {
}
