// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:46bf8f12750d18b99c312a8580717a0915edc26fab7f4218f7b18bd519522338
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Excel/spreadsheet format metadata.
 *
 * Identifies the document as a spreadsheet source via the {@code FormatMetadata::Excel}
 * discriminant. Sheet count and sheet names are stored inside this struct.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExcelMetadataBuilder.class)
public record ExcelMetadata(
    /** Number of sheets in the workbook. */
    @Nullable @JsonProperty("sheet_count") Long sheetCount,
    /** Names of all sheets in the workbook. */
    @Nullable @JsonProperty("sheet_names") List<String> sheetNames
) {
    public static ExcelMetadataBuilder builder() {
        return new ExcelMetadataBuilder();
    }
}
