// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ea969b2b0fb73f83ed099d84cb4293cc9b433229c33212fd4c922032d7e312f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * General extraction result used by the core extraction API.
 *
 * This is the main result type returned by all extraction functions.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExtractionResultBuilder.class)
public record ExtractionResult(
    String content,
    @JsonProperty("mime_type") String mimeType,
    Metadata metadata,
    @Nullable @JsonProperty("extraction_method") ExtractionMethod extractionMethod,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<Table> tables,
    @Nullable @JsonProperty("detected_languages") List<String> detectedLanguages,
    @Nullable List<Chunk> chunks,
    @Nullable List<ExtractedImage> images,
    @Nullable List<PageContent> pages,
    @Nullable List<Element> elements,
    @Nullable @JsonProperty("djot_content") DjotContent djotContent,
    @Nullable @JsonProperty("ocr_elements") List<OcrElement> ocrElements,
    @Nullable DocumentStructure document,
    @Nullable @JsonProperty("extracted_keywords") List<Keyword> extractedKeywords,
    @Nullable @JsonProperty("quality_score") Double qualityScore,
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("processing_warnings") List<ProcessingWarning> processingWarnings,
    @Nullable List<PdfAnnotation> annotations,
    @Nullable List<ArchiveEntry> children,
    @Nullable List<Uri> uris,
    @Nullable @JsonProperty("structured_output") Object structuredOutput,
    @Nullable @JsonProperty("code_intelligence") String codeIntelligence,
    @Nullable @JsonProperty("llm_usage") List<LlmUsage> llmUsage,
    @Nullable @JsonProperty("formatted_content") String formattedContent,
    @Nullable @JsonProperty("ocr_internal_document") String ocrInternalDocument
) {
    public static ExtractionResultBuilder builder() {
        return new ExtractionResultBuilder();
    }

    /**
     * Parse a {@code ExtractionResult} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static ExtractionResult fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ExtractionResult.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse ExtractionResult from JSON: " + e.getMessage(), e);
        }
    }
}
