// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d9beeb1a98bca2028e399fa045907a35cf809f433eb068df1ff9031c15141be9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * General extraction result used by the core extraction API.
 *
 * This is the main result type returned by all extraction functions.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExtractionResult.Builder.class)
public record ExtractionResult(
    String content,
    @JsonProperty("mime_type") String mimeType,
    Metadata metadata,
    /**
     * Extraction strategy used to produce the returned text.
     *
     * Populated when the extractor can reliably distinguish native text extraction,
     * OCR-only extraction, or mixed native/OCR output.
     */
    @Nullable @JsonProperty("extraction_method") ExtractionMethod extractionMethod,
    List<Table> tables,
    @Nullable @JsonProperty("detected_languages") List<String> detectedLanguages,
    /**
     * Text chunks when chunking is enabled.
     *
     * When chunking configuration is provided, the content is split into
     * overlapping chunks for efficient processing. Each chunk contains the text,
     * optional embeddings (if enabled), and metadata about its position.
     */
    @Nullable List<Chunk> chunks,
    /**
     * Extracted images from the document.
     *
     * When image extraction is enabled via {@code ImageExtractionConfig}, this field
     * contains all images found in the document with their raw data and metadata.
     * Each image may optionally contain a nested {@code ocr_result} if OCR was performed.
     */
    @Nullable List<ExtractedImage> images,
    /**
     * Per-page content when page extraction is enabled.
     *
     * When page extraction is configured, the document is split into per-page content
     * with tables and images mapped to their respective pages.
     */
    @Nullable List<PageContent> pages,
    /**
     * Semantic elements when element-based result format is enabled.
     *
     * When result_format is set to ElementBased, this field contains semantic
     * elements with type classification, unique identifiers, and metadata for
     * Unstructured-compatible element-based processing.
     */
    @Nullable List<Element> elements,
    /**
     * Rich Djot content structure (when extracting Djot documents).
     *
     * When extracting Djot documents with structured extraction enabled,
     * this field contains the full semantic structure including:
     * - Block-level elements with nesting
     * - Inline formatting with attributes
     * - Links, images, footnotes
     * - Math expressions
     * - Complete attribute information
     *
     * The {@code content} field still contains plain text for backward compatibility.
     *
     * Always {@code None} for non-Djot documents.
     */
    @Nullable @JsonProperty("djot_content") DjotContent djotContent,
    /**
     * OCR elements with full spatial and confidence metadata.
     *
     * When OCR is performed with element extraction enabled, this field contains
     * the structured representation of detected text including:
     * - Bounding geometry (rectangles or quadrilaterals)
     * - Confidence scores (detection and recognition)
     * - Rotation information
     * - Hierarchical relationships (Tesseract only)
     *
     * This field preserves all metadata that would otherwise be lost when
     * converting to plain text or markdown output formats.
     *
     * Only populated when {@code OcrElementConfig.include_elements} is true.
     */
    @Nullable @JsonProperty("ocr_elements") List<OcrElement> ocrElements,
    /**
     * Structured document tree (when document structure extraction is enabled).
     *
     * When {@code include_document_structure} is true in {@code ExtractionConfig}, this field
     * contains the full hierarchical representation of the document including:
     * - Heading-driven section nesting
     * - Table grids with cell-level metadata
     * - Content layer classification (body, header, footer, footnote)
     * - Inline text annotations (formatting, links)
     * - Bounding boxes and page numbers
     *
     * Independent of {@code result_format} — can be combined with Unified or ElementBased.
     */
    @Nullable DocumentStructure document,
    /**
     * Extracted keywords when keyword extraction is enabled.
     *
     * When keyword extraction (RAKE or YAKE) is configured, this field contains
     * the extracted keywords with scores, algorithm info, and position data.
     * Previously stored in {@code metadata.additional["keywords"]}.
     */
    @Nullable @JsonProperty("extracted_keywords") List<Keyword> extractedKeywords,
    /**
     * Document quality score from quality analysis.
     *
     * A value between 0.0 and 1.0 indicating the overall text quality.
     * Previously stored in {@code metadata.additional["quality_score"]}.
     */
    @Nullable @JsonProperty("quality_score") Double qualityScore,
    /**
     * Non-fatal warnings collected during processing pipeline stages.
     *
     * Captures errors from optional pipeline features (embedding, chunking,
     * language detection, output formatting) that don't prevent extraction
     * but may indicate degraded results.
     * Previously stored as individual keys in {@code metadata.additional}.
     */
    @JsonProperty("processing_warnings") List<ProcessingWarning> processingWarnings,
    /**
     * PDF annotations extracted from the document.
     *
     * When annotation extraction is enabled via {@code PdfConfig.extract_annotations},
     * this field contains text notes, highlights, links, stamps, and other
     * annotations found in PDF documents.
     */
    @Nullable List<PdfAnnotation> annotations,
    /**
     * Nested extraction results from archive contents.
     *
     * When extracting archives, each processable file inside produces its own
     * full extraction result. Set to {@code None} for non-archive formats.
     * Use {@code max_archive_depth} in config to control recursion depth.
     */
    @Nullable List<ArchiveEntry> children,
    /**
     * URIs/links discovered during document extraction.
     *
     * Contains hyperlinks, image references, citations, email addresses, and
     * other URI-like references found in the document. Always extracted when
     * present in the source document.
     */
    @Nullable List<Uri> uris,
    /**
     * Structured extraction output from LLM-based JSON schema extraction.
     *
     * When {@code structured_extraction} is configured in {@code ExtractionConfig}, the
     * extracted document content is sent to a VLM with the provided JSON schema.
     * The response is parsed and stored here as a JSON value matching the schema.
     */
    @Nullable @JsonProperty("structured_output") Object structuredOutput,
    /**
     * Code intelligence results from tree-sitter analysis.
     *
     * Populated when extracting source code files with the {@code tree-sitter} feature.
     * Contains metrics, structural analysis, imports/exports, comments,
     * docstrings, symbols, diagnostics, and optionally chunked code segments.
     */
    @Nullable @JsonProperty("code_intelligence") String codeIntelligence,
    /**
     * LLM token usage and cost data for all LLM calls made during this extraction.
     *
     * Contains one entry per LLM call. Multiple entries are produced when
     * VLM OCR, structured extraction, and/or LLM embeddings all run during
     * the same extraction.
     *
     * {@code None} when no LLM was used.
     */
    @Nullable @JsonProperty("llm_usage") List<LlmUsage> llmUsage,
    /**
     * Pre-rendered content in the requested output format.
     *
     * Populated during {@code derive_extraction_result} before tree derivation consumes
     * element data. {@code apply_output_format} swaps this into {@code content} at the end
     * of the pipeline, after post-processors have operated on plain text.
     */
    @Nullable @JsonProperty("formatted_content") String formattedContent,
    /**
     * Structured hOCR document for the OCR+layout pipeline.
     *
     * When tesseract produces hOCR output, the parsed {@code InternalDocument} carries
     * paragraph structure with bounding boxes and confidence scores. The layout
     * classification step enriches these elements before final rendering.
     */
    @Nullable @JsonProperty("ocr_internal_document") String ocrInternalDocument
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("content")
        private String content = "";
        @JsonProperty("mime_type")
        private String mimeType = "";
        @JsonProperty("metadata")
        private Metadata metadata = null;
        @JsonProperty("extraction_method")
        private Optional<ExtractionMethod> extractionMethod = Optional.empty();
        @JsonProperty("tables")
        private List<Table> tables = List.of();
        @JsonProperty("detected_languages")
        private Optional<List<String>> detectedLanguages = Optional.empty();
        @JsonProperty("chunks")
        private Optional<List<Chunk>> chunks = Optional.empty();
        @JsonProperty("images")
        private Optional<List<ExtractedImage>> images = Optional.empty();
        @JsonProperty("pages")
        private Optional<List<PageContent>> pages = Optional.empty();
        @JsonProperty("elements")
        private Optional<List<Element>> elements = Optional.empty();
        @JsonProperty("djot_content")
        private Optional<DjotContent> djotContent = Optional.empty();
        @JsonProperty("ocr_elements")
        private Optional<List<OcrElement>> ocrElements = Optional.empty();
        @JsonProperty("document")
        private Optional<DocumentStructure> document = Optional.empty();
        @JsonProperty("extracted_keywords")
        private Optional<List<Keyword>> extractedKeywords = Optional.empty();
        @JsonProperty("quality_score")
        private Optional<Double> qualityScore = Optional.empty();
        @JsonProperty("processing_warnings")
        private List<ProcessingWarning> processingWarnings = List.of();
        @JsonProperty("annotations")
        private Optional<List<PdfAnnotation>> annotations = Optional.empty();
        @JsonProperty("children")
        private Optional<List<ArchiveEntry>> children = Optional.empty();
        @JsonProperty("uris")
        private Optional<List<Uri>> uris = Optional.empty();
        @JsonProperty("structured_output")
        private Optional<Object> structuredOutput = Optional.empty();
        @JsonProperty("code_intelligence")
        private Optional<String> codeIntelligence = Optional.empty();
        @JsonProperty("llm_usage")
        private Optional<List<LlmUsage>> llmUsage = Optional.empty();
        @JsonProperty("formatted_content")
        private Optional<String> formattedContent = Optional.empty();
        @JsonProperty("ocr_internal_document")
        private Optional<String> ocrInternalDocument = Optional.empty();

        /** Sets the content field. */
        @JsonProperty("content")
        public Builder withContent(final String value) {
            this.content = value;
            return this;
        }

        /** Sets the mimeType field. */
        @JsonProperty("mime_type")
        public Builder withMimeType(final String value) {
            this.mimeType = value;
            return this;
        }

        /** Sets the metadata field. */
        @JsonProperty("metadata")
        public Builder withMetadata(final Metadata value) {
            this.metadata = value;
            return this;
        }

        /** Sets the extractionMethod field. */
        @JsonProperty("extraction_method")
        public Builder withExtractionMethod(final @Nullable ExtractionMethod value) {
            this.extractionMethod = Optional.ofNullable(value);
            return this;
        }

        /** Sets the tables field. */
        @JsonProperty("tables")
        public Builder withTables(final List<Table> value) {
            this.tables = value;
            return this;
        }

        /** Sets the detectedLanguages field. */
        @JsonProperty("detected_languages")
        public Builder withDetectedLanguages(final @Nullable List<String> value) {
            this.detectedLanguages = Optional.ofNullable(value);
            return this;
        }

        /** Sets the chunks field. */
        @JsonProperty("chunks")
        public Builder withChunks(final @Nullable List<Chunk> value) {
            this.chunks = Optional.ofNullable(value);
            return this;
        }

        /** Sets the images field. */
        @JsonProperty("images")
        public Builder withImages(final @Nullable List<ExtractedImage> value) {
            this.images = Optional.ofNullable(value);
            return this;
        }

        /** Sets the pages field. */
        @JsonProperty("pages")
        public Builder withPages(final @Nullable List<PageContent> value) {
            this.pages = Optional.ofNullable(value);
            return this;
        }

        /** Sets the elements field. */
        @JsonProperty("elements")
        public Builder withElements(final @Nullable List<Element> value) {
            this.elements = Optional.ofNullable(value);
            return this;
        }

        /** Sets the djotContent field. */
        @JsonProperty("djot_content")
        public Builder withDjotContent(final @Nullable DjotContent value) {
            this.djotContent = Optional.ofNullable(value);
            return this;
        }

        /** Sets the ocrElements field. */
        @JsonProperty("ocr_elements")
        public Builder withOcrElements(final @Nullable List<OcrElement> value) {
            this.ocrElements = Optional.ofNullable(value);
            return this;
        }

        /** Sets the document field. */
        @JsonProperty("document")
        public Builder withDocument(final @Nullable DocumentStructure value) {
            this.document = Optional.ofNullable(value);
            return this;
        }

        /** Sets the extractedKeywords field. */
        @JsonProperty("extracted_keywords")
        public Builder withExtractedKeywords(final @Nullable List<Keyword> value) {
            this.extractedKeywords = Optional.ofNullable(value);
            return this;
        }

        /** Sets the qualityScore field. */
        @JsonProperty("quality_score")
        public Builder withQualityScore(final @Nullable Double value) {
            this.qualityScore = Optional.ofNullable(value);
            return this;
        }

        /** Sets the processingWarnings field. */
        @JsonProperty("processing_warnings")
        public Builder withProcessingWarnings(final List<ProcessingWarning> value) {
            this.processingWarnings = value;
            return this;
        }

        /** Sets the annotations field. */
        @JsonProperty("annotations")
        public Builder withAnnotations(final @Nullable List<PdfAnnotation> value) {
            this.annotations = Optional.ofNullable(value);
            return this;
        }

        /** Sets the children field. */
        @JsonProperty("children")
        public Builder withChildren(final @Nullable List<ArchiveEntry> value) {
            this.children = Optional.ofNullable(value);
            return this;
        }

        /** Sets the uris field. */
        @JsonProperty("uris")
        public Builder withUris(final @Nullable List<Uri> value) {
            this.uris = Optional.ofNullable(value);
            return this;
        }

        /** Sets the structuredOutput field. */
        @JsonProperty("structured_output")
        public Builder withStructuredOutput(final @Nullable Object value) {
            this.structuredOutput = Optional.ofNullable(value);
            return this;
        }

        /** Sets the codeIntelligence field. */
        @JsonProperty("code_intelligence")
        public Builder withCodeIntelligence(final @Nullable String value) {
            this.codeIntelligence = Optional.ofNullable(value);
            return this;
        }

        /** Sets the llmUsage field. */
        @JsonProperty("llm_usage")
        public Builder withLlmUsage(final @Nullable List<LlmUsage> value) {
            this.llmUsage = Optional.ofNullable(value);
            return this;
        }

        /** Sets the formattedContent field. */
        @JsonProperty("formatted_content")
        public Builder withFormattedContent(final @Nullable String value) {
            this.formattedContent = Optional.ofNullable(value);
            return this;
        }

        /** Sets the ocrInternalDocument field. */
        @JsonProperty("ocr_internal_document")
        public Builder withOcrInternalDocument(final @Nullable String value) {
            this.ocrInternalDocument = Optional.ofNullable(value);
            return this;
        }

        /** Builds the ExtractionResult instance. */
        public ExtractionResult build() {
            return new ExtractionResult(
                content,
                mimeType,
                metadata,
                extractionMethod.orElse(null),
                tables,
                detectedLanguages.orElse(null),
                chunks.orElse(null),
                images.orElse(null),
                pages.orElse(null),
                elements.orElse(null),
                djotContent.orElse(null),
                ocrElements.orElse(null),
                document.orElse(null),
                extractedKeywords.orElse(null),
                qualityScore.orElse(null),
                processingWarnings,
                annotations.orElse(null),
                children.orElse(null),
                uris.orElse(null),
                structuredOutput.orElse(null),
                codeIntelligence.orElse(null),
                llmUsage.orElse(null),
                formattedContent.orElse(null),
                ocrInternalDocument.orElse(null)
            );
        }
    }
    // CPD-ON
    /**
     * Convert from an OCR result.
     */
    public static ExtractionResult fromOcr(OcrExtractionResult ocr) {
        throw new UnsupportedOperationException("fromOcr is not yet bridged via JNI; use the Builder instead.");
    }
}
