// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:24566873eaab8f8f56de449ba269ffa677f89539c1976f4340091be5f2c9df00
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Image metadata extracted from an image file.
 */
public record ExtractedImageMetadata(
    /**
     * Image width in pixels
     */
    int width,
    /**
     * Image height in pixels
     */
    int height,
    /**
     * Image format (e.g., "PNG", "JPEG")
     */
    String format,
    /**
     * EXIF data if available
     */
    @JsonProperty("exif_data") Map<String, String> exifData
) {
}
