// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8ba3a986a11c389cf677b8c64ac27c24dd38349844eef399c2437b3ace173f7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Main extraction configuration.
 *
 * This struct contains all configuration options for the extraction process.
 * It can be loaded from TOML, YAML, or JSON files, or created programmatically.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExtractionConfigBuilder.class)
public record ExtractionConfig(
    public static ExtractionConfigBuilder builder() {
        return new ExtractionConfigBuilder();
    }}
}}
