// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:34316474db308af7d827995a2328a5c66551e5692fd7c327e0acc2bc64dee244
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * FictionBook (FB2) metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FictionBookMetadata.Builder.class)
public record FictionBookMetadata(
    List<String> genres,
    List<String> sequences,
    @Nullable String annotation
) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code FictionBookMetadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static FictionBookMetadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, FictionBookMetadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse FictionBookMetadata from JSON: " + e.getMessage(), e);
        }
    }

    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("genres")
        private List<String> genres = List.of();
        @JsonProperty("sequences")
        private List<String> sequences = List.of();
        @JsonProperty("annotation")
        private Optional<String> annotation = Optional.empty();

        /** Sets the genres field. */
        @JsonProperty("genres")
        public Builder withGenres(final List<String> value) {
            this.genres = value;
            return this;
        }

        /** Sets the sequences field. */
        @JsonProperty("sequences")
        public Builder withSequences(final List<String> value) {
            this.sequences = value;
            return this;
        }

        /** Sets the annotation field. */
        @JsonProperty("annotation")
        public Builder withAnnotation(final Optional<String> value) {
            this.annotation = value;
            return this;
        }

        /** Builds the FictionBookMetadata instance. */
        public FictionBookMetadata build() {
            return new FictionBookMetadata(
                genres,
                sequences,
                annotation.orElse(null)
            );
        }
    }
}
