// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8c4f633680557d14bcc8f1f0ca446ebba18665ade35ed025bb32002855043b64
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Hierarchy extraction configuration for PDF text structure analysis.
 *
 * Enables extraction of document hierarchy levels (H1-H6) based on font size
 * clustering and semantic analysis. When enabled, hierarchical blocks are
 * included in page content.
 */
public record HierarchyConfig(
    /** Enable hierarchy extraction */
    boolean enabled,
    /** Number of font size clusters to use for hierarchy levels (1-7) */
    @JsonProperty("k_clusters") long kClusters,
    /** Include bounding box information in hierarchy blocks */
    @JsonProperty("include_bbox") boolean includeBbox,
    /** OCR coverage threshold for smart OCR triggering (0.0-1.0) */
    @JsonProperty("ocr_coverage_threshold") Optional<Float> ocrCoverageThreshold
) {
    public static HierarchyConfigBuilder builder() {
        return new HierarchyConfigBuilder();
    }
}
