// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7ac80498adec1dc4c5bb2cf4cc479a3aaa99097954de9440cd8c4f51011f0687
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Hierarchy extraction configuration for PDF text structure analysis.
 *
 * Enables extraction of document hierarchy levels (H1-H6) based on font size clustering and semantic analysis. When
 * enabled, hierarchical blocks are included in page content.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class HierarchyConfigBuilder {

    private boolean enabled = true;
    private long kClusters = 0;
    private boolean includeBbox = true;
    private Optional<Float> ocrCoverageThreshold = Optional.empty();

    /** Sets the enabled field. */
    public HierarchyConfigBuilder withEnabled(final boolean value) {
        this.enabled = value;
        return this;
    }

    /** Sets the kClusters field. */
    public HierarchyConfigBuilder withKClusters(final long value) {
        this.kClusters = value;
        return this;
    }

    /** Sets the includeBbox field. */
    public HierarchyConfigBuilder withIncludeBbox(final boolean value) {
        this.includeBbox = value;
        return this;
    }

    /** Sets the ocrCoverageThreshold field. */
    public HierarchyConfigBuilder withOcrCoverageThreshold(final Optional<Float> value) {
        this.ocrCoverageThreshold = value;
        return this;
    }

    /** Builds the HierarchyConfig instance. */
    public HierarchyConfig build() {
        return new HierarchyConfig(enabled, kClusters, includeBbox, ocrCoverageThreshold.orElse(null));
    }
}
