// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:40a9aafdaa96ae380a97588a095e7129a4f7e4f7f5b36511b716e9078e1b6100
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Built-in HTML theme selection.
 */
public enum HtmlTheme {
	/** Sensible defaults: system font stack, neutral colours, readable line */
	Default("default"),
	/** GitHub Markdown-inspired palette and spacing. */
	GitHub("github"),
	/** Dark background, light text. */
	Dark("dark"),
	/** Minimal light theme with generous whitespace. */
	Light("light"),
	/**
	 * No built-in stylesheet emitted. CSS custom properties are still defined
	 */
	Unstyled("unstyled");

	/** The string value. */
	private final String value;

	HtmlTheme(final String value) {
		this.value = value;
	}

	/** Returns the string value. */
	@JsonValue
	public String getValue() {
		return value;
	}

	/** Creates an instance from a string value. */
	@JsonCreator
	public static HtmlTheme fromValue(final String value) {
		for (HtmlTheme e : values()) {
			if (e.value.equalsIgnoreCase(value)) {
				return e;
			}
		}
		throw new IllegalArgumentException("Unknown value: " + value);
	}
}
