// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1a3be38a3d24520d351867265f8bbcedd9ba15249ed1521aca815e467f1d4de6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for styled HTML output.
 *
 * When set on ExtractionConfig::html_output alongside {@code output_format = OutputFormat::Html}, the pipeline builds a
 * StyledHtmlRenderer(crate::rendering::StyledHtmlRenderer) instead of the plain comrak-based renderer.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HtmlOutputConfigBuilder.class)
public record HtmlOutputConfig(
        /** Inline CSS string injected into the output after the theme stylesheet. */
        @Nullable String css,
        /** Path to a CSS file loaded once at renderer construction time. */
        @JsonProperty("css_file") java.nio.file.@Nullable Path cssFile,
        /** Built-in colour/typography theme. Default: [{@code HtmlTheme::Unstyled}]. */
        HtmlTheme theme,
        /** CSS class prefix applied to every emitted class name. */
        @JsonProperty("class_prefix") String classPrefix,
        /** When {@code true} (default), write the resolved CSS into a {@code &lt;style&gt;} block */
        @JsonProperty("embed_css") boolean embedCss) {
    public static HtmlOutputConfigBuilder builder() {
        return new HtmlOutputConfigBuilder();
    }
}
