// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6baa21786f8730ac3d2fe8f7ff3d68ec9fa9413264a7d7a00df80590c2bc5bd5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Image extraction configuration.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ImageExtractionConfig(
        /** Extract images from documents */
        @JsonProperty("extract_images") boolean extractImages,
        /** Target DPI for image normalization */
        @JsonProperty("target_dpi") int targetDpi,
        /** Maximum dimension for images (width or height) */
        @JsonProperty("max_image_dimension") int maxImageDimension,
        /** Whether to inject image reference placeholders into markdown output. */
        @JsonProperty("inject_placeholders") boolean injectPlaceholders,
        /** Automatically adjust DPI based on image content */
        @JsonProperty("auto_adjust_dpi") boolean autoAdjustDpi,
        /** Minimum DPI threshold */
        @JsonProperty("min_dpi") int minDpi,
        /** Maximum DPI threshold */
        @JsonProperty("max_dpi") int maxDpi,
        /** Maximum number of image objects to extract per PDF page. */
        @JsonProperty("max_images_per_page") Optional<Integer> maxImagesPerPage,
        /** When {@code true} (default), extracted images are classified by kind and grouped */
        boolean classify) {
    public static ImageExtractionConfigBuilder builder() {
        return new ImageExtractionConfigBuilder();
    }
    public ImageExtractionConfig {
        if (targetDpi == 0)
            targetDpi = 300;
        if (maxImageDimension == 0)
            maxImageDimension = 4096;
        if (minDpi == 0)
            minDpi = 72;
        if (maxDpi == 0)
            maxDpi = 600;
    }
}
