// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9d5ed4c0fc00a0c933bbe8c2e559ccbf281ab9acb765444f34f6ffacf186abac
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * Result of OCR extraction from an image with optional page tracking.
 */
@SuppressWarnings("checkstyle:LineLength")
public record ImageOcrResult(
    /** Extracted text content */
    String content,
    /** Character byte boundaries per frame (for multi-frame TIFFs) */
    @Nullable List<PageBoundary> boundaries,
    /** Per-frame content information */
    @Nullable @JsonProperty("page_contents") List<PageContent> pageContents
) {
}
