// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7466a9e831ae6f8bccfc1aa488d46d48b231503c964e7b6d5846f574921727e2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Image element metadata.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ImageMetadataType(
    /** Image source (URL, data URI, or SVG content) */
    String src,
    /** Alternative text from alt attribute */
    @Nullable String alt,
    /** Title attribute */
    @Nullable String title,
    /** Image dimensions as (width, height) if available */
    @Nullable List<Integer> dimensions,
    /** Image type classification */
    @JsonProperty("image_type") ImageType imageType,
    /** Additional attributes as key-value pairs */
    @JsonInclude(JsonInclude.Include.NON_NULL) List<String> attributes
) {
}
