// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:752ecb7f75dea9f2640e7c7e13c5fc6b6302dc25454331176504fa82faf0b7ff
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Image preprocessing metadata.
 *
 * Tracks the transformations applied to an image during OCR preprocessing,
 * including DPI normalization, resizing, and resampling.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ImagePreprocessingMetadata(
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("original_dimensions") List<Long> originalDimensions,
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("original_dpi") List<Double> originalDpi,
    @JsonProperty("target_dpi") int targetDpi,
    @JsonProperty("scale_factor") double scaleFactor,
    @JsonProperty("auto_adjusted") boolean autoAdjusted,
    @JsonProperty("final_dpi") int finalDpi,
    @Nullable @JsonProperty("new_dimensions") List<Long> newDimensions,
    @JsonProperty("resample_method") String resampleMethod,
    @JsonProperty("dimension_clamped") boolean dimensionClamped,
    @Nullable @JsonProperty("calculated_dpi") Integer calculatedDpi,
    @JsonProperty("skipped_resize") boolean skippedResize,
    @Nullable @JsonProperty("resize_error") String resizeError
) {

    /**
     * Parse a {@code ImagePreprocessingMetadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static ImagePreprocessingMetadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ImagePreprocessingMetadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse ImagePreprocessingMetadata from JSON: " + e.getMessage(), e);
        }
    }
}
