// DO NOT EDIT - auto-generated by alef
// alef:hash:218c8d97064812eb3c1f02fa7f2223f34a23d049ddc194e9df4acf0c793cc281
package dev.kreuzberg;

public class ImageProcessingException extends KreuzbergErrorException {
    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
