// DO NOT EDIT - auto-generated by alef
// alef:hash:2ffafa44e0a501a14293722fe00c753266b31b7e8d290533d97c7bc0b427945c
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
