// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3afef51e2f310b67e29f3a7e1fb15f691ea9c6f7b7ec0fdae277f18cb6eca2d4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Keyword extraction configuration.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class KeywordConfigBuilder {

    @JsonProperty("algorithm")
    private KeywordAlgorithm algorithm = null;
    @JsonProperty("max_keywords")
    private long maxKeywords = 0;
    @JsonProperty("min_score")
    private float minScore = 0.0f;
    @JsonProperty("ngram_range")
    private List<Long> ngramRange = List.of();
    @JsonProperty("language")
    private Optional<String> language = Optional.empty();
    @JsonProperty("yake_params")
    private Optional<YakeParams> yakeParams = Optional.empty();
    @JsonProperty("rake_params")
    private Optional<RakeParams> rakeParams = Optional.empty();

    /** Sets the algorithm field. */
    @JsonProperty("algorithm")
    public KeywordConfigBuilder withAlgorithm(final KeywordAlgorithm value) {
        this.algorithm = value;
        return this;
    }

    /** Sets the maxKeywords field. */
    @JsonProperty("max_keywords")
    public KeywordConfigBuilder withMaxKeywords(final long value) {
        this.maxKeywords = value;
        return this;
    }

    /** Sets the minScore field. */
    @JsonProperty("min_score")
    public KeywordConfigBuilder withMinScore(final float value) {
        this.minScore = value;
        return this;
    }

    /** Sets the ngramRange field. */
    @JsonProperty("ngram_range")
    public KeywordConfigBuilder withNgramRange(final List<Long> value) {
        this.ngramRange = value;
        return this;
    }

    /** Sets the language field. */
    @JsonProperty("language")
    public KeywordConfigBuilder withLanguage(final Optional<String> value) {
        this.language = value;
        return this;
    }

    /** Sets the yakeParams field. */
    @JsonProperty("yake_params")
    public KeywordConfigBuilder withYakeParams(final Optional<YakeParams> value) {
        this.yakeParams = value;
        return this;
    }

    /** Sets the rakeParams field. */
    @JsonProperty("rake_params")
    public KeywordConfigBuilder withRakeParams(final Optional<RakeParams> value) {
        this.rakeParams = value;
        return this;
    }

    /** Builds the KeywordConfig instance. */
    public KeywordConfig build() {
        return new KeywordConfig(algorithm, maxKeywords, minScore, ngramRange, language.orElse(null), yakeParams.orElse(null),
                rakeParams.orElse(null));
    }
}
