// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:84e33ead5104379afe40bfcbd6f2c74ca5cc67a5f7d4921c43b4fdca9f2bfbe4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Extracted keyword with metadata.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record Keyword(
        /** The keyword text. */
        String text,
        /** Relevance score (higher is better, algorithm-specific range). */
        float score,
        /** Algorithm that extracted this keyword. */
        KeywordAlgorithm algorithm,
        /** Optional positions where keyword appears in text (character offsets). */
        @Nullable List<Long> positions) {
}
