// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f61818cdd6a4c92172e8a7ea222b9005f0d764fc890301080c59e5230286f939
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * A detected layout region on a page.
 *
 * When layout detection is enabled, each page may have layout regions
 * identifying different content types (text, pictures, tables, etc.)
 * with confidence scores and spatial positions.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class LayoutRegionBuilder {

    private String className = "";
    private double confidence = 0.0;
    private String boundingBox = "";
    private double areaFraction = 0.0;

    /** Sets the className field. */
    public LayoutRegionBuilder withClassName(final String value) {
        this.className = value;
        return this;
    }

    /** Sets the confidence field. */
    public LayoutRegionBuilder withConfidence(final double value) {
        this.confidence = value;
        return this;
    }

    /** Sets the boundingBox field. */
    public LayoutRegionBuilder withBoundingBox(final String value) {
        this.boundingBox = value;
        return this;
    }

    /** Sets the areaFraction field. */
    public LayoutRegionBuilder withAreaFraction(final double value) {
        this.areaFraction = value;
        return this;
    }

    /** Builds the LayoutRegion instance. */
    public LayoutRegion build() {
        return new LayoutRegion(
            className,
            confidence,
            boundingBox,
            areaFraction
        );
    }
}
