// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cec33be59bd89cf7428b543cbf7afcdf167a5e856b514af7f5f0fed95aa25fd8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Link element metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record LinkMetadata(
    String href,
    String text,
    @Nullable String title,
    @JsonProperty("link_type") LinkType linkType,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<String> rel,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<String> attributes
) {
}
