// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:08e2fcd75d5274e3a1aee21f74c516bc17ef5c8e1abcbe8c4bc6873f94779b61
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Model manifest entry for cache management.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ManifestEntryResponse(
        /** Relative path within the cache directory */
        @JsonProperty("relative_path") String relativePath,
        /** SHA256 checksum of the model file */
        String sha256,
        /** Expected file size in bytes */
        @JsonProperty("size_bytes") long sizeBytes,
        /** HuggingFace source URL for downloading */
        @JsonProperty("source_url") String sourceUrl) {
}
