// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:797943c784c604d1d1ef3834a1bc67fa4588c695b87c351c1371e43867a978cc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A merged chunk produced by [{@code merge_segments}].
 */
public record MergedChunk(String text, @JsonProperty("byte_start") long byteStart,
        @JsonProperty("byte_end") long byteEnd) {
}
