// DO NOT EDIT - auto-generated by alef
// alef:hash:98b21caa7c4c37019336a7c930771ebada7eb163a94c5c9bdec211f40574c823
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
