// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:53097c6f4ae5def9ec4015d54ca2697889a80ff1416e42753520a6f921be3577
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Bounding geometry for an OCR element.
 *
 * Supports both axis-aligned rectangles (from Tesseract) and 4-point quadrilaterals
 * (from PaddleOCR and rotated text detection).
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({
    @JsonSubTypes.Type(value = OcrBoundingGeometry.Rectangle.class, name = "rectangle"),
    @JsonSubTypes.Type(value = OcrBoundingGeometry.Quadrilateral.class, name = "quadrilateral")
})
public sealed interface OcrBoundingGeometry {

    /** Axis-aligned bounding box (typical for Tesseract output). */
    record Rectangle(
        @JsonProperty("left") int left,
        @JsonProperty("top") int top,
        @JsonProperty("width") int width,
        @JsonProperty("height") int height
    ) implements OcrBoundingGeometry {
    }

    /** 4-point quadrilateral for rotated/skewed text (PaddleOCR). */
    record Quadrilateral(@JsonProperty("points") String points) implements OcrBoundingGeometry { }
}
