// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:275ab96805c82f74c0257ea5f81977493315433bf7b16aeb9938da974c7b0e33
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OCR backend types.
 */
public enum OcrBackendType {
    /** Tesseract OCR (native Rust binding) */
    Tesseract("tesseract"),
    /** EasyOCR (Python-based, via FFI) */
    EasyOCR("easyocr"),
    /** PaddleOCR (Python-based, via FFI) */
    PaddleOCR("paddleocr"),
    /** Custom/third-party OCR backend */
    Custom("custom");

    /** The string value. */
    private final String value;

    OcrBackendType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static OcrBackendType fromValue(final String value) {
        for (OcrBackendType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
