// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9b75d339da6d7d77121079d2098af208f13107be53fb7ed1b61e960be23ce048
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jetbrains.annotations.Nullable;

/**
 * Confidence scores for an OCR element.
 *
 * Separates detection confidence (how confident that text exists at this location) from recognition confidence (how
 * confident about the actual text content).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = OcrConfidenceBuilder.class)
public record OcrConfidence(@Nullable Double detection, double recognition) {
    public static OcrConfidenceBuilder builder() {
        return new OcrConfidenceBuilder();
    }
}
