// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d206b3e71ce2f52d5d0467e35cfaf6c7dfdc15531b24504b3005eb829a30b89b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Configuration for PaddleOCR backend.
 *
 * Configures PaddleOCR text detection and recognition with multi-language support. Uses a builder pattern for convenient configuration.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class PaddleOcrConfigBuilder {

    @JsonProperty("language")
    private String language = "";
    @JsonProperty("cache_dir")
    private Optional<java.nio.file.Path> cacheDir = Optional.empty();
    @JsonProperty("use_angle_cls")
    private boolean useAngleCls = false;
    @JsonProperty("enable_table_detection")
    private boolean enableTableDetection = false;
    @JsonProperty("det_db_thresh")
    private float detDbThresh = 0.0f;
    @JsonProperty("det_db_box_thresh")
    private float detDbBoxThresh = 0.0f;
    @JsonProperty("det_db_unclip_ratio")
    private float detDbUnclipRatio = 0.0f;
    @JsonProperty("det_limit_side_len")
    private int detLimitSideLen = 0;
    @JsonProperty("rec_batch_num")
    private int recBatchNum = 0;
    @JsonProperty("padding")
    private int padding = 0;
    @JsonProperty("drop_score")
    private float dropScore = 0.0f;
    @JsonProperty("model_tier")
    private String modelTier = "";

    /** Sets the language field. */
    @JsonProperty("language")
    public PaddleOcrConfigBuilder withLanguage(final String value) {
        this.language = value;
        return this;
    }

    /** Sets the cacheDir field. */
    @JsonProperty("cache_dir")
    public PaddleOcrConfigBuilder withCacheDir(final Optional<java.nio.file.Path> value) {
        this.cacheDir = value;
        return this;
    }

    /** Sets the useAngleCls field. */
    @JsonProperty("use_angle_cls")
    public PaddleOcrConfigBuilder withUseAngleCls(final boolean value) {
        this.useAngleCls = value;
        return this;
    }

    /** Sets the enableTableDetection field. */
    @JsonProperty("enable_table_detection")
    public PaddleOcrConfigBuilder withEnableTableDetection(final boolean value) {
        this.enableTableDetection = value;
        return this;
    }

    /** Sets the detDbThresh field. */
    @JsonProperty("det_db_thresh")
    public PaddleOcrConfigBuilder withDetDbThresh(final float value) {
        this.detDbThresh = value;
        return this;
    }

    /** Sets the detDbBoxThresh field. */
    @JsonProperty("det_db_box_thresh")
    public PaddleOcrConfigBuilder withDetDbBoxThresh(final float value) {
        this.detDbBoxThresh = value;
        return this;
    }

    /** Sets the detDbUnclipRatio field. */
    @JsonProperty("det_db_unclip_ratio")
    public PaddleOcrConfigBuilder withDetDbUnclipRatio(final float value) {
        this.detDbUnclipRatio = value;
        return this;
    }

    /** Sets the detLimitSideLen field. */
    @JsonProperty("det_limit_side_len")
    public PaddleOcrConfigBuilder withDetLimitSideLen(final int value) {
        this.detLimitSideLen = value;
        return this;
    }

    /** Sets the recBatchNum field. */
    @JsonProperty("rec_batch_num")
    public PaddleOcrConfigBuilder withRecBatchNum(final int value) {
        this.recBatchNum = value;
        return this;
    }

    /** Sets the padding field. */
    @JsonProperty("padding")
    public PaddleOcrConfigBuilder withPadding(final int value) {
        this.padding = value;
        return this;
    }

    /** Sets the dropScore field. */
    @JsonProperty("drop_score")
    public PaddleOcrConfigBuilder withDropScore(final float value) {
        this.dropScore = value;
        return this;
    }

    /** Sets the modelTier field. */
    @JsonProperty("model_tier")
    public PaddleOcrConfigBuilder withModelTier(final String value) {
        this.modelTier = value;
        return this;
    }

    /** Builds the PaddleOcrConfig instance. */
    public PaddleOcrConfig build() {
        return new PaddleOcrConfig(language, cacheDir.orElse(null), useAngleCls, enableTableDetection, detDbThresh, detDbBoxThresh,
                detDbUnclipRatio, detLimitSideLen, recBatchNum, padding, dropScore, modelTier);
    }
}
