// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8ba56d27e6a4c995a28c7974208b1451be4d0ac5b347bb982902f4dfa4f2cd5a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Metadata for individual page/slide/sheet.
 *
 * Captures per-page information including dimensions, content counts, and visibility state (for presentations).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record PageInfo(
        /** Page number (1-indexed) */
        long number,
        /** Page title (usually for presentations) */
        Optional<String> title,
        /** Dimensions in points (PDF) or pixels (images): (width, height) */
        Optional<List<Double>> dimensions,
        /** Number of images on this page */
        @JsonProperty("image_count") Optional<Long> imageCount,
        /** Number of tables on this page */
        @JsonProperty("table_count") Optional<Long> tableCount,
        /** Whether this page is hidden (e.g., in presentations) */
        Optional<Boolean> hidden,
        /** Whether this page is blank (no meaningful text, no images, no tables) */
        @JsonProperty("is_blank") Optional<Boolean> isBlank,
        /** Whether this page contains non-trivial vector graphics (paths, shapes, curves) */
        @JsonProperty("has_vector_graphics") boolean hasVectorGraphics) {
}
