// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2a99833ca4cb142f4885a5fda3ca55864da70b421023a2e10f228cea2b1dfaa3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type of paginated unit in a document.
 *
 * Distinguishes between different types of "pages" (PDF pages, presentation
 * slides, spreadsheet sheets).
 */
public enum PageUnitType {
	/** Standard document pages (PDF, DOCX, images) */
	Page("page"),
	/** Presentation slides (PPTX, ODP) */
	Slide("slide"),
	/** Spreadsheet sheets (XLSX, ODS) */
	Sheet("sheet");

	/** The string value. */
	private final String value;

	PageUnitType(final String value) {
		this.value = value;
	}

	/** Returns the string value. */
	@JsonValue
	public String getValue() {
		return value;
	}

	/** Creates an instance from a string value. */
	@JsonCreator
	public static PageUnitType fromValue(final String value) {
		for (PageUnitType e : values()) {
			if (e.value.equalsIgnoreCase(value)) {
				return e;
			}
		}
		throw new IllegalArgumentException("Unknown value: " + value);
	}
}
