// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1f6c658177accea6f9233f97acc64a561d4cb0ad9ae9d4f20aa943fb17f13086
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Page margins converted to points (1/72 inch).
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonDeserialize(builder = PageMarginsPointsBuilder.class)
public record PageMarginsPoints(
    @Nullable Double top,
    @Nullable Double right,
    @Nullable Double bottom,
    @Nullable Double left,
    @Nullable Double header,
    @Nullable Double footer,
    @Nullable Double gutter
) {
    public static PageMarginsPointsBuilder builder() {
        return new PageMarginsPointsBuilder();
    }
}
