// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:916efeddcd1d865a83b9a8f314f22a80157284c639742f8d20642583eb4bf0aa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * PDF-specific configuration.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PdfConfigBuilder.class)
public record PdfConfig(
    @JsonProperty("extract_images") boolean extractImages,
    @Nullable List<String> passwords,
    @JsonProperty("extract_metadata") boolean extractMetadata,
    @Nullable HierarchyConfig hierarchy,
    @JsonProperty("extract_annotations") boolean extractAnnotations,
    @Nullable @JsonProperty("top_margin_fraction") Float topMarginFraction,
    @Nullable @JsonProperty("bottom_margin_fraction") Float bottomMarginFraction,
    @JsonProperty("allow_single_column_tables") boolean allowSingleColumnTables
) {
    public static PdfConfigBuilder builder() {
        return new PdfConfigBuilder();
    }
}
