// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4466fa371f159255983053b687935dbe09bfff9d13f1d37bc02871c6fa490125
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Application properties from docProps/app.xml for PPTX
 *
 * Contains PowerPoint-specific document metadata.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class PptxAppPropertiesBuilder {

    private Optional<String> application = Optional.empty();
    private Optional<String> appVersion = Optional.empty();
    private Optional<Integer> totalTime = Optional.empty();
    private Optional<String> company = Optional.empty();
    private Optional<Integer> docSecurity = Optional.empty();
    private Optional<Boolean> scaleCrop = Optional.empty();
    private Optional<Boolean> linksUpToDate = Optional.empty();
    private Optional<Boolean> sharedDoc = Optional.empty();
    private Optional<Boolean> hyperlinksChanged = Optional.empty();
    private Optional<Integer> slides = Optional.empty();
    private Optional<Integer> notes = Optional.empty();
    private Optional<Integer> hiddenSlides = Optional.empty();
    private Optional<Integer> multimediaClips = Optional.empty();
    private Optional<String> presentationFormat = Optional.empty();
    private List<String> slideTitles = List.of();

    /** Sets the application field. */
    public PptxAppPropertiesBuilder withApplication(final Optional<String> value) {
        this.application = value;
        return this;
    }

    /** Sets the appVersion field. */
    public PptxAppPropertiesBuilder withAppVersion(final Optional<String> value) {
        this.appVersion = value;
        return this;
    }

    /** Sets the totalTime field. */
    public PptxAppPropertiesBuilder withTotalTime(final Optional<Integer> value) {
        this.totalTime = value;
        return this;
    }

    /** Sets the company field. */
    public PptxAppPropertiesBuilder withCompany(final Optional<String> value) {
        this.company = value;
        return this;
    }

    /** Sets the docSecurity field. */
    public PptxAppPropertiesBuilder withDocSecurity(final Optional<Integer> value) {
        this.docSecurity = value;
        return this;
    }

    /** Sets the scaleCrop field. */
    public PptxAppPropertiesBuilder withScaleCrop(final Optional<Boolean> value) {
        this.scaleCrop = value;
        return this;
    }

    /** Sets the linksUpToDate field. */
    public PptxAppPropertiesBuilder withLinksUpToDate(final Optional<Boolean> value) {
        this.linksUpToDate = value;
        return this;
    }

    /** Sets the sharedDoc field. */
    public PptxAppPropertiesBuilder withSharedDoc(final Optional<Boolean> value) {
        this.sharedDoc = value;
        return this;
    }

    /** Sets the hyperlinksChanged field. */
    public PptxAppPropertiesBuilder withHyperlinksChanged(final Optional<Boolean> value) {
        this.hyperlinksChanged = value;
        return this;
    }

    /** Sets the slides field. */
    public PptxAppPropertiesBuilder withSlides(final Optional<Integer> value) {
        this.slides = value;
        return this;
    }

    /** Sets the notes field. */
    public PptxAppPropertiesBuilder withNotes(final Optional<Integer> value) {
        this.notes = value;
        return this;
    }

    /** Sets the hiddenSlides field. */
    public PptxAppPropertiesBuilder withHiddenSlides(final Optional<Integer> value) {
        this.hiddenSlides = value;
        return this;
    }

    /** Sets the multimediaClips field. */
    public PptxAppPropertiesBuilder withMultimediaClips(final Optional<Integer> value) {
        this.multimediaClips = value;
        return this;
    }

    /** Sets the presentationFormat field. */
    public PptxAppPropertiesBuilder withPresentationFormat(final Optional<String> value) {
        this.presentationFormat = value;
        return this;
    }

    /** Sets the slideTitles field. */
    public PptxAppPropertiesBuilder withSlideTitles(final List<String> value) {
        this.slideTitles = value;
        return this;
    }

    /** Builds the PptxAppProperties instance. */
    public PptxAppProperties build() {
        return new PptxAppProperties(application.orElse(null), appVersion.orElse(null), totalTime.orElse(null),
                company.orElse(null), docSecurity.orElse(null), scaleCrop.orElse(null), linksUpToDate.orElse(null),
                sharedDoc.orElse(null), hyperlinksChanged.orElse(null), slides.orElse(null), notes.orElse(null),
                hiddenSlides.orElse(null), multimediaClips.orElse(null), presentationFormat.orElse(null), slideTitles);
    }
}
