// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:04fda40afeb9ea071f3eda7091f0d1c3fd95ab490070f021573649e825b4e9eb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * PowerPoint presentation metadata.
 *
 * Extracted from PPTX files containing slide counts and presentation details.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PptxMetadataBuilder.class)
public record PptxMetadata(
    /** Total number of slides in the presentation */
    @JsonProperty("slide_count") long slideCount,
    /** Names of slides (if available) */
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("slide_names") List<String> slideNames,
    /** Number of embedded images */
    @Nullable @JsonProperty("image_count") Long imageCount,
    /** Number of tables */
    @Nullable @JsonProperty("table_count") Long tableCount
) {
    public static PptxMetadataBuilder builder() {
        return new PptxMetadataBuilder();
    }
}
