// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:002f5ae4dfe8bff770591861bf62ee1d70af34f8aaa89888ce5a6482984cc6a8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * PowerPoint presentation metadata.
 *
 * Extracted from PPTX files containing slide counts and presentation details.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record PptxMetadata(
        /** Total number of slides in the presentation */
        @JsonProperty("slide_count") long slideCount,
        /** Names of slides (if available) */
        @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("slide_names") List<String> slideNames,
        /** Number of embedded images */
        @JsonProperty("image_count") Optional<Long> imageCount, /** Number of tables */
        @JsonProperty("table_count") Optional<Long> tableCount) {
    public static PptxMetadataBuilder builder() {
        return new PptxMetadataBuilder();
    }
}
