// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c77d1574e170a1f242d0e1da90f95740714b0f2002a6677dfdd02e1a159f520a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A non-fatal warning from a processing pipeline stage.
 *
 * Captures errors from optional features that don't prevent extraction but may indicate degraded results.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ProcessingWarning(String source, String message) {
}
