// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f4a136a17023698df0e82366f585b2303b5d937b67b2345221769dd4ca765dab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Page Segmentation Mode for Tesseract OCR
 */
public enum PSMMode {
    OsdOnly("osdonly"),
    AutoOsd("autoosd"),
    AutoOnly("autoonly"),
    Auto("auto"),
    SingleColumn("singlecolumn"),
    SingleBlockVertical("singleblockvertical"),
    SingleBlock("singleblock"),
    SingleLine("singleline"),
    SingleWord("singleword"),
    CircleWord("circleword"),
    SingleChar("singlechar");

    /** The string value. */
    private final String value;

    PSMMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PSMMode fromValue(final String value) {
        for (PSMMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
