// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:080f69c543174018ce0238e4d389f0c8777e20031e7b09c54ec3795de9c9d562
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Outlook PST archive metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PstMetadataBuilder.class)
public record PstMetadata(@JsonProperty("message_count") long messageCount) {
    public static PstMetadataBuilder builder() {
        return new PstMetadataBuilder();
    }

    /**
     * Parse a {@code PstMetadata} from a JSON string.
     *
     * @param json
     *            JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException
     *             if the JSON cannot be deserialised.
     */
    public static PstMetadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper().registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                    .findAndRegisterModules().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                    .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                    .readValue(json, PstMetadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse PstMetadata from JSON: " + e.getMessage(), e);
        }
    }
}
