// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:312e3c47da1be23adf12c2b2d5e4d7564a4a9c4d1c617f349e90c6ac079d1e23
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Outlook PST archive metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PstMetadataBuilder.class)
public record PstMetadata(@JsonProperty("message_count") long messageCount) {
    public static PstMetadataBuilder builder() {
        return new PstMetadataBuilder();
    }
}
