// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a978a83c574f9bb550c3a6cf000f91bc46746a5e726e0bf65836ae5d684631e6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Fully resolved (flattened) style after walking the inheritance chain.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class ResolvedStyleBuilder {

    private String paragraphProperties = "";
    private String runProperties = "";

    /** Sets the paragraphProperties field. */
    public ResolvedStyleBuilder withParagraphProperties(final String value) {
        this.paragraphProperties = value;
        return this;
    }

    /** Sets the runProperties field. */
    public ResolvedStyleBuilder withRunProperties(final String value) {
        this.runProperties = value;
        return this;
    }

    /** Builds the ResolvedStyle instance. */
    public ResolvedStyle build() {
        return new ResolvedStyle(paragraphProperties, runProperties);
    }
}
