// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:02cea7db97f37e8723814d1716533d13c64a1ec4aacb60f531c64b36263d39bc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Fully resolved (flattened) style after walking the inheritance chain.
 */
@JsonDeserialize(builder = ResolvedStyleBuilder.class)
public record ResolvedStyle(@JsonProperty("paragraph_properties") String paragraphProperties,
        @JsonProperty("run_properties") String runProperties) {
    public static ResolvedStyleBuilder builder() {
        return new ResolvedStyleBuilder();
    }
}
