// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7d62a7b9020086f6a2b9aea4e2ab62c86179aee004c24be2eb3fee0759f791bc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * API server configuration.
 *
 * This struct holds all configuration options for the Kreuzberg API server,
 * including host/port settings, CORS configuration, and upload limits.
 *
 * # Defaults
 *
 * - {@code host}: "127.0.0.1" (localhost only)
 * - {@code port}: 8000
 * - {@code cors_origins}: empty vector (allows all origins)
 * - {@code max_request_body_bytes}: 104_857_600 (100 MB)
 * - {@code max_multipart_field_bytes}: 104_857_600 (100 MB)
 */
@JsonPOJOBuilder(withPrefix = "with")
public class ServerConfigBuilder {

    private String host = "";
    private short port = 0;
    private List<String> corsOrigins = List.of();
    private long maxRequestBodyBytes = 0;
    private long maxMultipartFieldBytes = 0;

    /** Sets the host field. */
    public ServerConfigBuilder withHost(final String value) {
        this.host = value;
        return this;
    }}

    /** Sets the port field. */
    public ServerConfigBuilder withPort(final short value) {
        this.port = value;
        return this;
    }}

    /** Sets the corsOrigins field. */
    public ServerConfigBuilder withCorsOrigins(final List<String> value) {
        this.corsOrigins = value;
        return this;
    }}

    /** Sets the maxRequestBodyBytes field. */
    public ServerConfigBuilder withMaxRequestBodyBytes(final long value) {
        this.maxRequestBodyBytes = value;
        return this;
    }}

    /** Sets the maxMultipartFieldBytes field. */
    public ServerConfigBuilder withMaxMultipartFieldBytes(final long value) {
        this.maxMultipartFieldBytes = value;
        return this;
    }}

    /** Builds the ServerConfig instance. */
    public ServerConfig build() {
        return new ServerConfig(
    }}
}}
