// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1638d19cafdda9b137352c02fe3cfd76a2c0b58f5c4d1d6dd5b06b9ac7e86e6f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Structured data (Schema.org, microdata, RDFa) block.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record StructuredData(
        /** Type of structured data */
        @JsonProperty("data_type") StructuredDataType dataType,
        /** Raw JSON string representation */
        @JsonProperty("raw_json") String rawJson,
        /** Schema type if detectable (e.g., "Article", "Event", "Product") */
        @Nullable @JsonProperty("schema_type") String schemaType) {
}
