// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9bb92f8e60c63a44cac0760d556a611b5d8ecbef9449e4ee143a777b31600026
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record StructuredDataResult(String content, String format, Map<String, String> metadata,
        @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("text_fields") List<String> textFields) {
}
