// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a5f97284e2db3bcb4196617d8a6f21d7a11267719886f9a4cc696fcfe75063ab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A single style definition parsed from {@code <w:style>} in {@code word/styles.xml}.
 */
public record StyleDefinition(
    /** The style ID ({@code w:styleId} attribute). */
    String id,
    /** Human-readable name ({@code <w:name w:val="..."/>}). */
    Optional<String> name,
    /** Style type: paragraph, character, table, or numbering. */
    @JsonProperty("style_type") String styleType,
    /** ID of the parent style ({@code <w:basedOn w:val="..."/>}). */
    @JsonProperty("based_on") Optional<String> basedOn,
    /** ID of the style to apply to the next paragraph ({@code <w:next w:val="..."/>}). */
    @JsonProperty("next_style") Optional<String> nextStyle,
    /** Whether this is the default style for its type. */
    @JsonProperty("is_default") boolean isDefault,
    /** Paragraph properties defined directly on this style. */
    @JsonProperty("paragraph_properties") String paragraphProperties,
    /** Run properties defined directly on this style. */
    @JsonProperty("run_properties") String runProperties
) {
}
