// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c2b907c5a22df9754f8e12fd329ab5bae085f6376de61b3b934c5305c495bd94
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Structured table grid with cell-level metadata.
 *
 * Stores row/column dimensions and a flat list of cells with position info.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonPOJOBuilder(withPrefix = "with")
public class TableGridBuilder {

    private int rows = 0;
    private int cols = 0;
    private List<GridCell> cells = List.of();

    /** Sets the rows field. */
    public TableGridBuilder withRows(final int value) {
        this.rows = value;
        return this;
    }

    /** Sets the cols field. */
    public TableGridBuilder withCols(final int value) {
        this.cols = value;
        return this;
    }

    /** Sets the cells field. */
    public TableGridBuilder withCells(final List<GridCell> value) {
        this.cells = value;
        return this;
    }

    /** Builds the TableGrid instance. */
    public TableGrid build() {
        return new TableGrid(rows, cols, cells);
    }
}
