// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:126b56ce296bb22400a23e63cdb310521eeec5bb1cd868f19ac1d03711492eab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import org.jspecify.annotations.Nullable;

/**
 * Table-level properties from {@code &lt;w:tblPr&gt;}.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TablePropertiesBuilder.class)
public record TableProperties(
    @Nullable @JsonProperty("style_id") String styleId,
    @Nullable String width,
    @Nullable String alignment,
    @Nullable String layout,
    @Nullable String look,
    @Nullable String borders,
    @Nullable @JsonProperty("cell_margins") String cellMargins,
    @Nullable String indent,
    @Nullable String caption
) {
    public static TablePropertiesBuilder builder() {
        return new TablePropertiesBuilder();
    }
}
