// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3d208a955532c7b1dfbfcf0466ba9f3b1a35a56fbf0d2084d3fdd88a3ed920c4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * Structured table grid with cell-level metadata.
 *
 * Stores row/column dimensions and a flat list of cells with position info.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TableGridBuilder.class)
public record TableGrid(
    public static TableGridBuilder builder() {
        return new TableGridBuilder();
    }}
}}
