// DO NOT EDIT - auto-generated by alef
// alef:hash:3633a09cc7e8e73c39a8235236039b9200b6dd51d1d1263d7aeebb05edf6a525
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
