// DO NOT EDIT - auto-generated by alef
// alef:hash:36a4eb6544d64fe0bbae804982df8280cfbc91c77b8c4b6587788ca604ee0d97
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
	/** Creates a new TimeoutException with the given message. */
	public TimeoutException(final String message) {
		super(message);
	}

	/** Creates a new TimeoutException with the given message and cause. */
	public TimeoutException(final String message, final Throwable cause) {
		super(message, cause);
	}
}
