// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9a1942097da09f8b80e18ac41ba556c530254c0311e83b6d8cf4d9ec3ed7e8d2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Cache warm request.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record WarmRequest(
        /** Download all embedding model presets */
        @JsonProperty("all_embeddings") boolean allEmbeddings, /** Specific embedding model preset to download */
        @JsonProperty("embedding_model") Optional<String> embeddingModel) {
    public static WarmRequestBuilder builder() {
        return new WarmRequestBuilder();
    }
}
