// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2cf0028bc67d180f121360c8d4f3e5e3e8c939cc42ad089bc1f284f030f614cb
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * XML metadata extracted during XML parsing.
 *
 * Provides statistics about XML document structure.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class XmlMetadataBuilder {

    @JsonProperty("element_count")
    private long elementCount = 0;
    @JsonProperty("unique_elements")
    private List<String> uniqueElements = List.of();

    /** Sets the elementCount field. */
    public XmlMetadataBuilder withElementCount(final long value) {
        this.elementCount = value;
        return this;
    }

    /** Sets the uniqueElements field. */
    public XmlMetadataBuilder withUniqueElements(final List<String> value) {
        this.uniqueElements = value;
        return this;
    }

    /** Builds the XmlMetadata instance. */
    public XmlMetadata build() {
        return new XmlMetadata(
            elementCount,
            uniqueElements
        );
    }
}
