// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0c560623c5062537ad0246835615d1402e64204410086c4bcded2504f4d8f58a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Year range for bibliographic metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record YearRange(
    @Nullable Integer min,
    @Nullable Integer max,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<Integer> years
) {

    /**
     * Parse a {@code YearRange} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static YearRange fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, YearRange.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse YearRange from JSON: " + e.getMessage(), e);
        }
    }
}
