// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c221f4156a9d069255401a31fcf4bbcc94409a9024882814feee30673edf7ebf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Helper struct for validating ZIP archives for security issues.
 */
public class ZipBombValidator implements AutoCloseable {
    private final MemorySegment handle;

    ZipBombValidator(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_ZIP_BOMB_VALIDATOR_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free ZipBombValidator: " + e.getMessage(), e);
            }
        }
    }
}
