// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:14d32d89c014679cbb9534b491bd3f1bf4eab9f11259d0ffbf709cc73794dd5f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Helper struct for validating ZIP archives for security issues.
 */
public class ZipBombValidator implements AutoCloseable {
	private final MemorySegment handle;

	ZipBombValidator(MemorySegment handle) {
		this.handle = handle;
	}

	MemorySegment handle() {
		return this.handle;
	}

	@Override
	public void close() {
		if (handle != null && !handle.equals(MemorySegment.NULL)) {
			try {
				NativeLib.KREUZBERG_ZIP_BOMB_VALIDATOR_FREE.invoke(handle);
			} catch (Throwable e) {
				throw new RuntimeException("Failed to free ZipBombValidator: " + e.getMessage(), e);
			}
		}
	}
}
