# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ffda1727c1aa2594a1f2efa40d2cc0e581a273ad9a76400f558e5c49d5825646
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AccelerationConfig do
  @moduledoc "Hardware acceleration configuration for ONNX Runtime models."

  defstruct provider: :auto,
            device_id: 0
end
