# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:687f384d14198ac9d38dbfc0a82da5deda40545267c7eb2b6aaff9ee1d2707df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveMetadata do
  @moduledoc "Archive (ZIP/TAR/7Z) metadata."

  defstruct format: "",
            file_count: 0,
            file_list: [],
            total_size: 0,
            compressed_size: 0
end
