# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d79a2a05d0e874881e3e0cf6d59457e630abbc723cc9166ff32858aca5ec326c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkSizing do
  @moduledoc "How chunk size is measured."

  @type t :: term()

  @type characters :: :characters
  @type tokenizer :: %{type: :tokenizer, model: term(), cache_dir: term()}
end
