# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0b04c84906f323ffa71e9b4c8379451e9b451fa24e1f5ada17b27a7eb3eb4e90
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkMetadata do
  @moduledoc "Metadata about a chunk's position in the original document."

  defstruct byte_start: 0,
            byte_end: 0,
            token_count: nil,
            chunk_index: 0,
            total_chunks: 0,
            first_page: nil,
            last_page: nil,
            heading_context: nil
end
