# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5614667ed959b7c05b9749b4511ec7bc38a1979a6ec71387cb8f79e544979ea5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Chunk do
  @moduledoc "A text chunk with optional embedding and metadata."

  defstruct content: "",
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
