# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:47bfc2878c60c656273e35a0ff7179313c2c63851c7e7d11791e60b4bf280f03
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CitationMetadata do
  @moduledoc "Citation file metadata (RIS, PubMed, EndNote)."

  defstruct citation_count: 0,
            format: "",
            authors: [],
            year_range: nil,
            dois: [],
            keywords: []
end
