# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:29c3a502811019bec7087507550b34eb65075282ee2a2ce640220e0028fb2fdb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CitationMetadata do
  @moduledoc "Citation file metadata (RIS, PubMed, EndNote)."

  defstruct citation_count: 0,
            format: "",
            authors: [],
            year_range: nil,
            dois: [],
            keywords: []
end
