# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:17d1d717e2aa870cfb0b6dba3cf452a6657c3eafa7f4c1884a94b9293dd8e773
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  defstruct name: "",
            role: nil
end
