# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4c5b10cfdf09ab92c1c00acb449e4cc6df375eb265db69f9e5b22fc7fc2b78a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  defstruct name: "",
            role: nil
end
