# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e9b71e78904b232054105e01994fd58687b3de6432e48dc8db8f5e063e8cf46c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  defstruct name: "",
            field_type: ""
end
