# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9796cad32e0c789ac2222447593c30797933be063b7627f910ef4b74a06770c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  defstruct name: "",
            field_type: ""
end
