# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:137cad93357348286fd8b513f85d20428e9465c0637ccb8442270a924f8efc5d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectedBoundary do
  @moduledoc "A detected structural boundary in the text."

  defstruct byte_offset: 0,
            is_header: false
end
