# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:be6abcd88f446bea4c85661be7e257cd0ccd59b85587b8ed18995501902e191f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxMetadata do
  @moduledoc "Word document metadata."

  defstruct core_properties: nil,
            app_properties: nil,
            custom_properties: %{}
end
