# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4ac4bc01c19a8b17fd7624f572b21292f8e777525eb8829c419b19c935028d51
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc "Email attachment representation."

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
