# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f777e640b55c2be85f717626d6df51c9d39e8d1f6a9920a7095986922fa7b90
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingConfig do
  @moduledoc "Embedding configuration for text chunks."

  defstruct model: :preset,
            normalize: true,
            batch_size: 32,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_embed_duration_secs: 0
end
