# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:58f3e599b21413578c54bd0281d5f53ed9a24150181c4ac5c2e8c7cc46af5ec5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
