# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:10ba73113526e62f09dd102f2a27f0e82df9f5e4a5fcbde0b096af3f69fa1550
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
