# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bd5a509d733a36b3257c1acab4a83c4187153debbc44f33da5bab12fbd3d954b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
