# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:74e63fba192c67a3315e0c4f665b81f385a375eb5a3b16ca0f7b0c03660c81a4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedTextParams do
  @moduledoc "Request parameters for embedding generation."

  defstruct texts: [],
            preset: nil,
            model: nil,
            api_key: nil,
            embedding_plugin: nil
end
