# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ffd0bbd0aa05d8e5eed89aa55561dca6f8cc3a0045b742488e1b89c7936914f8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingPreset do
  @moduledoc "Preset configurations for common RAG use cases."

  defstruct name: "",
            chunk_size: 0,
            overlap: 0,
            model_repo: "",
            pooling: "",
            model_file: "",
            dimensions: 0,
            description: ""
end
