# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a72213d3a0f5704fa6c78bdb1553c139255bb7f6f99daccf4bdda5cc8a04817a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc "Excel workbook representation."

  defstruct sheets: [],
            metadata: %{}
end
