# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4b96a776aab3ce872000db32373c57aa3670cc5e6b72db2d62a54bd28dd9dbd8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelSheet do
  @moduledoc "Single Excel worksheet."

  defstruct name: "",
            markdown: "",
            row_count: 0,
            col_count: 0,
            cell_count: 0,
            table_cells: nil
end
