# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:66d280e8c72017a27a7962421132c4eba3866dafa34568c4d2f748d1cc6578d5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc "Excel workbook representation."

  defstruct sheets: [],
            metadata: %{}
end
