# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4c2b418ac5095abf957ff3f10085fae7bb4c2180576c8a31264b0aa5847f5e63
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractionMethod do  @moduledoc "How the extracted text was produced."  @type t :: :native | :ocr | :mixed
  @native :native  @ocr :ocr  @mixed :mixed
  @spec native() :: t()
  def native, do: @native  @spec ocr() :: t()
  def ocr, do: @ocr  @spec mixed() :: t()
  def mixed, do: @mixedend
