# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b7f8376ed9ed8571a6600fa7a16f152f29516a78bb4bab2d01c645ad8bb60812
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  defstruct genres: [],
            sequences: [],
            annotation: ""
end
