# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c5fe071e9d43a9025be285e5ce964ddf25806bd14174862e53002ceee0782f6c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FileExtractionConfig do
  @moduledoc "Per-file extraction configuration overrides for batch processing."

  defstruct enable_quality_processing: false,
            ocr: nil,
            force_ocr: false,
            force_ocr_pages: [],
            disable_ocr: false,
            chunking: nil,
            content_filter: nil,
            images: nil,
            pdf_options: nil,
            token_reduction: nil,
            language_detection: nil,
            pages: nil,
            keywords: nil,
            postprocessor: nil,
            html_options: "",
            result_format: :unified,
            output_format: :plain,
            include_document_structure: false,
            layout: nil,
            timeout_secs: 0,
            tree_sitter: nil,
            structured_extraction: nil
end
