# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5b50444a275d32003ac5bf072a2353ad2c62750f7bb2bf08e266f4b81d299bf5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  defstruct label: "",
            content: []
end
