# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dc2cab48839d3c385e808a2d8bba9e3306cec2436a3b6d3d26833db815c0256b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  defstruct level: 0,
            text: ""
end
