# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e54c6a47e386956be12cf4952193f130fece36fb8e8d6381e8f7bd82c05f08f7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingContext do
  @moduledoc "Heading context for a chunk within a Markdown document."

  defstruct headings: []
end
