# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d53bd782e25ffcb3d698cbf09b81d8420dcd8faa9c3df3a3dadef3ae3340c871
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingContext do
  @moduledoc "Heading context for a chunk within a Markdown document."

  defstruct headings: []
end
