# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e9f1aa9f413e7a5bbdf67d7d3f36a698755f1363bd5a4c9e5202ac1424f998dd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchyConfig do
  @moduledoc "Hierarchy extraction configuration for PDF text structure analysis."

  defstruct enabled: true,
            k_clusters: 3,
            include_bbox: true,
            ocr_coverage_threshold: nil
end
