# This file is auto-generated by alef. DO NOT EDIT.
defmodule Kreuzberg.HierarchyBlock do
  @moduledoc "A TextBlock with hierarchy level assignment."

  defstruct text: "",
            bbox: "",
            font_size: 0.0,
            hierarchy_level: ""
end
