# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3a389095713ee6f717f3d833717832cbb53c0de059199966e647df8c883695c9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc "A text block with hierarchy level assignment."

  defstruct text: "",
            font_size: 0.0,
            level: "",
            bbox: nil
end
