# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcf658b4404240150e6265ed4944c0f94c55cebcd1f5b5fbcfaaaae45a6159f6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadata do
  @moduledoc "Image metadata extracted from image files."

  defstruct width: 0,
            height: 0,
            format: "",
            exif: %{}
end
