# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f192be6cfe7a3652b60309f7b2880c4039e5439b70d00e76fa3dc78775593a55
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImagePreprocessingConfig do  @moduledoc "Image preprocessing configuration for OCR."  defstruct target_dpi: 300,
            auto_rotate: true,
            deskew: true,
            denoise: false,
            contrast_enhance: false,
            binarization_method: "otsu",
            invert_colors: false
end
