# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dcf020f8ee5eaf399595fac17cac56d6099a735ac8124f60e684561814f9a924
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  defstruct copyright: "",
            license: "",
            history_dates: %{},
            contributor_roles: []
end
