# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c0ee2f89265c3dc5f0a3a09d4a7efaaf7220c055a019e7456c8f54f1b1f3c4b8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @spec yake() :: t()
  def yake, do: @yake
  @spec rake() :: t()
  def rake, do: @rake
end
