# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:86c117b1227d6c3693e179fdd40f18c21cb1994af430cc25dee9713a75b81d40
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  defstruct enabled: true,
            min_confidence: 0.8,
            detect_multiple: false
end
