# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e2551ef5753923a759fb9e00c4000e58f41394bc1d72fe59d0879ab12473a8f5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  defstruct enabled: true,
            min_confidence: 0.8,
            detect_multiple: false
end
