# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f181549243e5a844e1ac550ae8987227b770b20728e9ad61de3b2c55ef4a129e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetection do  @moduledoc "A single layout detection result."  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
