# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c00af466552c7521f0bdbb2816388216371e7763d326cc3cef73adba3dbc47ae
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ManifestEntryResponse do
  @moduledoc "Model manifest entry for cache management."

  defstruct relative_path: "",
            sha256: "",
            size_bytes: 0,
            source_url: ""
end
