# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:127407fd5567326045b4de35306716c0f17757720e0261607a0fcf5385812d09
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrMetadata do  @moduledoc "OCR processing metadata."  defstruct language: "",
            psm: 0,
            output_format: "",
            table_count: 0,
            table_rows: 0,
            table_cols: 0
end
