# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83e4935cb46c8ffb3b5cd7d97ffc711fa8de8e74a302f68b235bf6f9f3e3c322
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  defstruct detection: 0.0,
            recognition: 0.0
end
