# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4d01a2ee3b460745c8153e39cd548deec04d6ec74ddb5faf8014b2b320db3b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElement do
  @moduledoc "A unified OCR element representing detected text with full metadata."

  defstruct text: "",
            geometry: :rectangle,
            confidence: nil,
            level: :line,
            rotation: nil,
            page_number: 0,
            parent_id: "",
            backend_metadata: %{}
end
