# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e05bff56943578a2ae8db954f1f2314de8dafbc490a7fc40204fee970ef73d1e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrCacheStats do
  @moduledoc false

  defstruct total_files: 0,
            total_size_mb: 0.0
end
