# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0d0281a82b4b0a25d79b7346a5194fd8ce1b679641fcaac14e0c253d3015190a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementLevel do
  @moduledoc "Hierarchical level of an OCR element."

  @type t :: :word | :line | :block | :page

  @word :word
  @line :line
  @block :block
  @page :page

  @spec word() :: t()
  def word, do: @word
  @spec line() :: t()
  def line, do: @line
  @spec block() :: t()
  def block, do: @block
  @spec page() :: t()
  def page, do: @page
end
