# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:be0dc5724523e24f76eb3fd6624ee62a4b08386fdb92772ee75c4343562606a1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc "Multi-backend OCR pipeline with quality-based fallback."

  defstruct stages: [],
            quality_thresholds: nil
end
