# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f83c9dea8935cd13c8a2a1ef6babd9edbac05d77f05387c874e56a56d27bc577
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrBoundingGeometry do
  @moduledoc "Bounding geometry for an OCR element."

  @type t :: term()

  @type rectangle :: %{type: :rectangle, left: term(), top: term(), width: term(), height: term()}
  @type quadrilateral :: %{type: :quadrilateral, points: term()}
end
