# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:20d20ace13eeb8ca2841ed37fd877ff117287a580def7c83859967711c57eb35
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElement do
  @moduledoc "A unified OCR element representing detected text with full metadata."

  defstruct text: "",
            geometry: :rectangle,
            confidence: nil,
            level: :line,
            rotation: nil,
            page_number: 0,
            parent_id: "",
            backend_metadata: %{}
end
