# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:37d8497f65564584bf17bf5244bf5c794d5296e271e66d5858aaec2686006487
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  defstruct backend: "",
            priority: 0,
            language: nil,
            tesseract_config: nil,
            paddle_ocr_config: nil,
            vlm_config: nil
end
