# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:19c3a3b0434649883c569d06fe86a0715ad986bf16c67fdeee3185e832a179f5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  defstruct detection: 0.0,
            recognition: 0.0
end
