# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c099d8ba9ed305848aea18bfeb68224988991c474c701623bf8141b489c13c1f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrMetadata do
  @moduledoc "OCR processing metadata."

  defstruct language: "",
            psm: 0,
            output_format: "",
            table_count: 0,
            table_rows: 0,
            table_cols: 0
end
