# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:06aed76e0fcae3002802878970ed105da88c2620250c9c6758bd7be84db1ca7e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
