# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f65aa9081100727c1293b51b48a86a5b107b45f0d64852df83f60341d98d072e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OdtProperties do
  @moduledoc "OpenDocument metadata from meta.xml"

  defstruct title: "",
            subject: "",
            creator: "",
            initial_creator: "",
            keywords: "",
            description: "",
            date: "",
            creation_date: "",
            language: "",
            generator: "",
            editing_duration: "",
            editing_cycles: "",
            page_count: 0,
            word_count: 0,
            character_count: 0,
            paragraph_count: 0,
            table_count: 0,
            image_count: 0
end
