# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:89ab4efe8b38c05071633b781927b78e4c1594594433ea271938f98ea3e4dd64
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OpenWebDocumentResponse do
  @moduledoc "OpenWebUI \"External\" engine response format."

  defstruct page_content: "",
            metadata: ""
end
