# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4480a77c1ee13b09d86acf6d7c11ec11d8adf7df1ffef28857f923810f3b3846
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OpenWebDocumentResponse do
  @moduledoc "OpenWebUI \"External\" engine response format."

  defstruct page_content: "",
            metadata: ""
end
