# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7e44654cab9b82049e607a5b23e4d8aace977cbc455d7139598b707bedc5ddf3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OutputFormat do
  @moduledoc "Output format for extraction results."

  @type t :: term()

  @type plain :: :plain
  @type markdown :: :markdown
  @type djot :: :djot
  @type html :: :html
  @type json :: :json
  @type structured :: :structured
  @type custom :: %{type: :custom, value_0: term()}
end
