# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da83507e06dcea02819cb88e678e272c118973f09bde81a13b5d415ce91b860f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageContent do
  @moduledoc "Content for a single page/slide."

  defstruct page_number: 0,
            content: "",
            tables: [],
            images: [],
            hierarchy: nil,
            is_blank: nil,
            layout_regions: nil
end
