# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e6a915d35e9d92315c7f9fae2059b47c498c3c927643a69a89f7b0a55194b5bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageConfig do
  @moduledoc "Page extraction and tracking configuration."

  defstruct extract_pages: false,
            insert_page_markers: false,
            marker_format: "

<!-- PAGE {page_num} -->

"
end
