# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3ee1a6a93edf6f2754369d5029fcc06f97df3025a26141c4aaced97f99357609
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageUnitType do
  @moduledoc "Type of paginated unit in a document."

  @type t :: :page | :slide | :sheet

  @page :page
  @slide :slide
  @sheet :sheet

  @spec page() :: t()
  def page, do: @page
  @spec slide() :: t()
  def slide, do: @slide
  @spec sheet() :: t()
  def sheet, do: @sheet
end
