# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e07f9f131341a422c771f21f7fcfae1eb21533f4fef65c29d6bcd341a84cc7e1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageContent do
  @moduledoc "Content for a single page/slide."

  defstruct page_number: 0,
            content: "",
            tables: [],
            images: [],
            hierarchy: nil,
            is_blank: nil,
            layout_regions: nil
end
