# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1e858c80bafa0ce2b9ef0b5067d9e6ff8aedc2bc2cb8f21e7a405ef3b9bcdac5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PoolError do
  @moduledoc "Error type for pool operations."

  @type t :: :lock_poisoned

  @lock_poisoned :lock_poisoned

  @spec lock_poisoned() :: t()
  def lock_poisoned, do: @lock_poisoned
end
