# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f365ea4feaa5dcb272fa72d72b8917ac7dee0e438e49b935241e28b4f1ce31d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil
end
