# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fbe4fbd8f2b8e8de84a025fb5bf018518216bbc698e93ba4d58ca81269a20fdd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc "A non-fatal warning from a processing pipeline stage."

  defstruct source: "",
            message: ""
end
