# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ad8bb350dd1a093edbf0227f135a7faaf9c78377e485e2d7aa91bcef78fcb87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  @typedoc "Outlook PST archive metadata."
  @type t :: %__MODULE__{
          message_count: non_neg_integer()
        }

  defstruct message_count: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Jason.Encoder.encode(opts)
    end
  end
end
