# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8e60ae94480cbb4471fcc815141dcdc66d1d14d0106b8ce955d7566c1fd16350
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ServerConfig do  @moduledoc "API server configuration."  defstruct host: "",
            port: 0,
            cors_origins: [],
            max_request_body_bytes: 0,
            max_multipart_field_bytes: 0
end
