# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:27fd7dfb9b0db9b3de3eec4f41887d9a206c3eeed7f8b3c99dbb69826ced65ea
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
