# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f20bec6f8d7a7ea9ca7f32622df20ea4c9ea8ec23e6387249f046eccf442d2f2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionResponse do
  @moduledoc "Response from structured extraction endpoint."

  defstruct structured_output: "",
            content: "",
            mime_type: ""
end
