# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c41b5ad8935ca1d06deef1a1317a0800dbd2c8a75d2d8b0a0387e39c3649b4e7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc "A supported document format entry."

  defstruct extension: "",
            mime_type: ""
end
