# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:426fff61f5a194ccfb6f09a97d0c059b19236d72b6f5411ab8187c89596d40ed
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextAnnotation do
  @moduledoc "Inline text annotation — byte-range based formatting and links."

  defstruct start: 0,
            end: 0,
            kind: :bold
end
