# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:63b0ab30f119187fa106e6eaa66738a8a57d3b77a3e9c24d143809af51112bf0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextMetadata do
  @moduledoc "Text/Markdown metadata."

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: [],
            links: [],
            code_blocks: []
end
