# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f0edeaf1ab8cee9df8be1db7aaf059bbaf25b383223c9b425d25ed62704b9fb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextMetadata do
  @moduledoc "Text/Markdown metadata."

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: [],
            links: [],
            code_blocks: []
end
