# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f8ea395033a9a6fce4e5f2e8ac348337c5c020b36bb1e0222abcc9b4c9a02e00
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  defstruct mode: "",
            preserve_important_words: true
end
