# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f821e70349f320c05428be674391f13f864bcaa88299b761b2dc68efd7b0f91
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterProcessConfig do
  @moduledoc "Processing options for tree-sitter code analysis."

  defstruct structure: true,
            imports: true,
            exports: true,
            comments: false,
            docstrings: false,
            symbols: false,
            diagnostics: false,
            chunk_max_size: nil,
            content_mode: :chunks
end
