// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Kreuzberg;
using Xunit;
using Kreuzberg.E2E;

namespace Kreuzberg.E2E.Pdf
{
    public class PdfTests
    {
        [SkippableFact]
        public void PdfAnnotations()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/test_article.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/test_article.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/test_article.pdf", true);
            var config = TestHelpers.BuildConfig("{\"pdf_options\":{\"extract_annotations\":true}}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertAnnotations(result, true, 1);
        }

        [SkippableFact]
        public void PdfAssemblyTechnical()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/assembly_language_for_beginners_al4_b_en.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/assembly_language_for_beginners_al4_b_en.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/assembly_language_for_beginners_al4_b_en.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 5000);
            TestHelpers.AssertContentContainsAny(result, new[] { "assembly", "register", "instruction" });
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "format_type", @"{""eq"": ""pdf""}");
        }

        [SkippableFact]
        public void PdfBayesianDataAnalysis()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/bayesian_data_analysis_third_edition_13th_feb_2020.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/bayesian_data_analysis_third_edition_13th_feb_2020.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/bayesian_data_analysis_third_edition_13th_feb_2020.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10000);
            TestHelpers.AssertContentContainsAny(result, new[] { "Bayesian", "probability", "distribution" });
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "format_type", @"{""eq"": ""pdf""}");
        }

        [SkippableFact]
        public void PdfBoundingBoxes()
        {
            TestHelpers.SkipIfFeatureUnavailable("pdf");
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/tiny.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/tiny.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/tiny.pdf", true);
            var config = TestHelpers.BuildConfig("{\"images\":{\"extract_images\":true}}");

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 50);
            TestHelpers.AssertTableCount(result, 1, null);
            TestHelpers.AssertTableBoundingBoxes(result);
        }

        [SkippableFact]
        public void PdfCodeAndFormula()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/code_and_formula.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/code_and_formula.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/code_and_formula.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 100);
        }

        [SkippableFact]
        public void PdfDeepLearning()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/fundamentals_of_deep_learning_2014.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/fundamentals_of_deep_learning_2014.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/fundamentals_of_deep_learning_2014.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 1000);
            TestHelpers.AssertContentContainsAny(result, new[] { "neural", "network", "deep learning" });
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "format_type", @"{""eq"": ""pdf""}");
        }

        [SkippableFact]
        public void PdfEmbeddedImages()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/embedded_images_tables.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/embedded_images_tables.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/embedded_images_tables.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 50);
            TestHelpers.AssertTableCount(result, 0, null);
        }

        [SkippableFact]
        public void PdfGoogleDoc()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/google_doc_document.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/google_doc_document.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/google_doc_document.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 50);
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "format_type", @"{""eq"": ""pdf""}");
        }

        [SkippableFact]
        public void PdfLargeCiml()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/a_course_in_machine_learning_ciml_v0_9_all.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/a_course_in_machine_learning_ciml_v0_9_all.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/a_course_in_machine_learning_ciml_v0_9_all.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10000);
            TestHelpers.AssertContentContainsAny(result, new[] { "machine learning", "algorithm", "training" });
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "format_type", @"{""eq"": ""pdf""}");
        }

        [SkippableFact]
        public void PdfNonEnglishGerman()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/5_level_paging_and_5_level_ept_intel_revision_1_1_may_2017.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/5_level_paging_and_5_level_ept_intel_revision_1_1_may_2017.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/5_level_paging_and_5_level_ept_intel_revision_1_1_may_2017.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 100);
            TestHelpers.AssertContentContainsAny(result, new[] { "Intel", "paging" });
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "format_type", @"{""eq"": ""pdf""}");
        }

        [SkippableFact]
        public void PdfRightToLeft()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/right_to_left_01.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/right_to_left_01.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/right_to_left_01.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 50);
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "format_type", @"{""eq"": ""pdf""}");
        }

        [SkippableFact]
        public void PdfSimpleText()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/fake_memo.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/fake_memo.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/fake_memo.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 50);
            TestHelpers.AssertContentContainsAny(result, new[] { "May 5, 2023", "To Whom it May Concern", "Mallori" });
        }

        [SkippableFact]
        public void PdfTablesLarge()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/large.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/large.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/large.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 500);
        }

        [SkippableFact]
        public void PdfTablesMedium()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/medium.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/medium.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/medium.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 100);
        }

        [SkippableFact]
        public void PdfTablesSmall()
        {
            TestHelpers.SkipIfFeatureUnavailable("ocr");
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/tiny.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/tiny.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/tiny.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 50);
            TestHelpers.AssertContentContainsAll(result, new[] { "Table 1", "Selected Numbers", "Celsius", "Fahrenheit", "Water Freezing Point", "Water Boiling Point" });
            TestHelpers.AssertTableCount(result, 1, null);
        }

        [SkippableFact]
        public void PdfTechnicalStatLearning()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdf/an_introduction_to_statistical_learning_with_applications_in_r_islr_sixth_printing.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdf/an_introduction_to_statistical_learning_with_applications_in_r_islr_sixth_printing.pdf");
            var documentPath = TestHelpers.EnsureDocument("pdf/an_introduction_to_statistical_learning_with_applications_in_r_islr_sixth_printing.pdf", true);
            var config = TestHelpers.BuildConfig(null);

            var result = KreuzbergClient.ExtractFileSync(documentPath, config);
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10000);
            TestHelpers.AssertContentContainsAny(result, new[] { "statistical", "regression", "learning" });
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "format_type", @"{""eq"": ""pdf""}");
        }

    }
}
