// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:10b191b3138f0a003b1c252b71e61adad2eb9959448027d23193db1291cd764c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import kreuzberg
import e2e_gleam

import gleam/option

// Graceful handling of empty bytes (should not error)
pub fn error_empty_bytes_test() {
  let assert Ok(data_bytes__) = e2e_gleam.read_file_bytes("../../test_documents/text/empty.txt")
  let result = kreuzberg.extract_bytes_sync(data_bytes__, "text/plain", kreuzberg.ExtractionConfig(use_cache: True, enable_quality_processing: True, ocr: option.None, force_ocr: False, force_ocr_pages: option.None, disable_ocr: False, chunking: option.None, content_filter: option.None, images: option.None, pdf_options: option.None, token_reduction: option.None, language_detection: option.None, pages: option.None, keywords: option.None, postprocessor: option.None, html_options: option.None, html_output: option.None, extraction_timeout_secs: option.None, max_concurrent_extractions: option.None, result_format: kreuzberg.Unified, security_limits: option.None, output_format: kreuzberg.Plain, layout: option.None, include_document_structure: False, acceleration: option.None, cache_namespace: option.None, cache_ttl_secs: option.None, email: option.None, concurrency: option.None, max_archive_depth: 10, tree_sitter: option.None, structured_extraction: option.None, cancel_token: option.None))
  result |> should.be_ok()
  let assert Ok(r) = result
}

// Error when extracting with empty MIME type
pub fn error_empty_mime_test() {
  let assert Ok(data_bytes__) = e2e_gleam.read_file_bytes("../../test_documents/text/plain.txt")
  kreuzberg.extract_bytes_sync(data_bytes__, "", kreuzberg.ExtractionConfig(use_cache: True, enable_quality_processing: True, ocr: option.None, force_ocr: False, force_ocr_pages: option.None, disable_ocr: False, chunking: option.None, content_filter: option.None, images: option.None, pdf_options: option.None, token_reduction: option.None, language_detection: option.None, pages: option.None, keywords: option.None, postprocessor: option.None, html_options: option.None, html_output: option.None, extraction_timeout_secs: option.None, max_concurrent_extractions: option.None, result_format: kreuzberg.Unified, security_limits: option.None, output_format: kreuzberg.Plain, layout: option.None, include_document_structure: False, acceleration: option.None, cache_namespace: option.None, cache_ttl_secs: option.None, email: option.None, concurrency: option.None, max_archive_depth: 10, tree_sitter: option.None, structured_extraction: option.None, cancel_token: option.None)) |> should.be_error()
}

// extract_bytes force+disable OCR
pub fn error_extract_bytes_conflicting_ocr_test() {
  let assert Ok(data_bytes__) = e2e_gleam.read_file_bytes("../../test_documents/text/fake_text.txt")
  kreuzberg.extract_bytes_sync(data_bytes__, "text/plain", kreuzberg.ExtractionConfig(use_cache: True, enable_quality_processing: True, ocr: option.None, force_ocr: True, force_ocr_pages: option.None, disable_ocr: True, chunking: option.None, content_filter: option.None, images: option.None, pdf_options: option.None, token_reduction: option.None, language_detection: option.None, pages: option.None, keywords: option.None, postprocessor: option.None, html_options: option.None, html_output: option.None, extraction_timeout_secs: option.None, max_concurrent_extractions: option.None, result_format: kreuzberg.Unified, security_limits: option.None, output_format: kreuzberg.Plain, layout: option.None, include_document_structure: False, acceleration: option.None, cache_namespace: option.None, cache_ttl_secs: option.None, email: option.None, concurrency: option.None, max_archive_depth: 10, tree_sitter: option.None, structured_extraction: option.None, cancel_token: option.None)) |> should.be_error()
}

// Error when extracting with invalid MIME type format
pub fn error_invalid_mime_format_test() {
  let assert Ok(data_bytes__) = e2e_gleam.read_file_bytes("../../test_documents/text/plain.txt")
  kreuzberg.extract_bytes_sync(data_bytes__, "not-a-mime", kreuzberg.ExtractionConfig(use_cache: True, enable_quality_processing: True, ocr: option.None, force_ocr: False, force_ocr_pages: option.None, disable_ocr: False, chunking: option.None, content_filter: option.None, images: option.None, pdf_options: option.None, token_reduction: option.None, language_detection: option.None, pages: option.None, keywords: option.None, postprocessor: option.None, html_options: option.None, html_output: option.None, extraction_timeout_secs: option.None, max_concurrent_extractions: option.None, result_format: kreuzberg.Unified, security_limits: option.None, output_format: kreuzberg.Plain, layout: option.None, include_document_structure: False, acceleration: option.None, cache_namespace: option.None, cache_ttl_secs: option.None, email: option.None, concurrency: option.None, max_archive_depth: 10, tree_sitter: option.None, structured_extraction: option.None, cancel_token: option.None)) |> should.be_error()
}

// Error when extracting with unsupported MIME type
pub fn error_unsupported_mime_test() {
  let assert Ok(data_bytes__) = e2e_gleam.read_file_bytes("../../test_documents/text/plain.txt")
  kreuzberg.extract_bytes_sync(data_bytes__, "application/x-nonexistent", kreuzberg.ExtractionConfig(use_cache: True, enable_quality_processing: True, ocr: option.None, force_ocr: False, force_ocr_pages: option.None, disable_ocr: False, chunking: option.None, content_filter: option.None, images: option.None, pdf_options: option.None, token_reduction: option.None, language_detection: option.None, pages: option.None, keywords: option.None, postprocessor: option.None, html_options: option.None, html_output: option.None, extraction_timeout_secs: option.None, max_concurrent_extractions: option.None, result_format: kreuzberg.Unified, security_limits: option.None, output_format: kreuzberg.Plain, layout: option.None, include_document_structure: False, acceleration: option.None, cache_namespace: option.None, cache_ttl_secs: option.None, email: option.None, concurrency: option.None, max_archive_depth: 10, tree_sitter: option.None, structured_extraction: option.None, cancel_token: option.None)) |> should.be_error()
}
