# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f58dec9a314687d1aaddc70423419c336bc679c04041137bf2a177cd4e89b833
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib kreuzberg, .registration = TRUE
NULL
