// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:59a46822932825bf0368dcf9101f94f1d6dd02a5219a5d7639c7cc2b6758eaa3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from 'vitest';
import { extractFile, extractFileSync, type WasmExtractionConfig } from 'kreuzberg';

describe('document', () => {
  it('doc_metadata_docx: Extract DOCX metadata', () => {
    const result = extractFileSync("vendored/markitdown/test.docx");
    expect(result.metadata.length).toBeGreaterThan(0);
  });

  it('doc_metadata_pdf: Extract PDF metadata', () => {
    const result = extractFileSync("pdf/fake_memo.pdf");
    expect(result.metadata.length).toBeGreaterThan(0);
  });

  it('doc_structure_docx: Extract DOCX document structure with include_document_structure config', () => {
    const result = extractFileSync("vendored/markitdown/test.docx", undefined, { includeDocumentStructure: true } as WasmExtractionConfig);
    expect((result.document ?? "").length).toBeGreaterThan(0);
  });

  it('doc_structure_html: Extract HTML document structure with include_document_structure config', () => {
    const result = extractFileSync("html/html.html", undefined, { includeDocumentStructure: true } as WasmExtractionConfig);
    expect((result.document ?? "").length).toBeGreaterThan(0);
  });

  it('doc_structure_pdf: Extract PDF document structure with include_document_structure config', () => {
    const result = extractFileSync("pdf/fake_memo.pdf", undefined, { includeDocumentStructure: true } as WasmExtractionConfig);
    expect((result.document ?? "").length).toBeGreaterThan(0);
  });
});
