// This file is auto-generated by alef. DO NOT EDIT.
import { describe, it, expect } from 'vitest';
import { extract_file, JsExtractionConfig } from 'kreuzberg';

describe('embeddings', () => {
  it('embedding_disabled: Tests chunking without embeddings - chunks should not have embedding vectors', async () => {
    const options = new JsExtractionConfig();
    options.chunking = { max_chars: 500, max_overlap: 50 };
    const result = await extract_file("pdf/fake_memo.pdf", options);
    expect(result.mimeType.trim()).toBe("application/pdf");
    // TODO: unsupported assertion type: min_length
    expect(result.chunks.length).toBeGreaterThanOrEqual(1);
    expect(result.chunksHaveContent).toBe(true);
  });
});
