// This file is auto-generated by alef. DO NOT EDIT.
import { describe, it, expect } from 'vitest';
import { extract_file, JsExtractionConfig } from 'kreuzberg';

describe('language', () => {
  it('lang_detect_config: Language detection with specific language config', async () => {
    const options = new JsExtractionConfig();
    options.languageDetection = { enabled: true, languages: ["en", "de", "fr"] };
    const result = await extract_file("semantic/mixed_topics.txt", options);
  });

  it('lang_detect_english: Language detection works on English text', async () => {
    const options = new JsExtractionConfig();
    options.languageDetection = { enabled: true };
    const result = await extract_file("semantic/mixed_topics.txt", options);
  });
});
