// This file is auto-generated by alef. DO NOT EDIT.
import { describe, it, expect } from 'vitest';
import { extract_file } from 'kreuzberg';

describe('validator_management', () => {
  it('validators_clear: Clear all validators and verify list is empty', async () => {
    const result = await extract_file('');
    expect(result.result.trim()).toHaveLength(0);
  });

  it('validators_list: List all registered validators', async () => {
    const result = await extract_file('');
  });
});
