# This file is auto-generated by alef. DO NOT EDIT.
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'chunking' do
  it 'chunk_batch_basic: Batch chunking of multiple texts in a single call' do
    result = Kreuzberg.extract_file('', Kreuzberg::ExtractionConfig.new(max_characters: 100, max_overlap: 10))
    expect(result).not_to be_nil
  end

  it 'chunk_text_basic: Basic text chunking with small chunk size and overlap' do
    result = Kreuzberg.extract_file('', Kreuzberg::ExtractionConfig.new(max_characters: 50, max_overlap: 10))
    expect(result).not_to be_nil
  end

  it 'chunk_text_large: Text chunking with large chunk size to test handling of long content' do
    result = Kreuzberg.extract_file('', Kreuzberg::ExtractionConfig.new(max_characters: 1000, max_overlap: 10))
    expect(result).not_to be_nil
  end

  it 'chunk_text_no_overlap: Text chunking with no overlap between chunks' do
    result = Kreuzberg.extract_file('', Kreuzberg::ExtractionConfig.new(max_characters: 50, max_overlap: 0))
    expect(result).not_to be_nil
  end

  it 'chunk_text_overlap_exceeds: chunk_text overlap >= max' do
    expect { Kreuzberg.extract_file('', Kreuzberg::ExtractionConfig.new(max_characters: 50, overlap: 60)) }.to raise_error
  end

  it 'chunk_text_yaml: Chunk with YAML chunker' do
    result = Kreuzberg.extract_file('', Kreuzberg::ExtractionConfig.new(chunker_type: 'yaml', max_characters: 50))
    expect(result).not_to be_nil
  end

  it 'chunk_text_zero_max: chunk_text max_characters zero' do
    expect { Kreuzberg.extract_file('', Kreuzberg::ExtractionConfig.new(max_characters: 0)) }.to raise_error
  end

  it 'chunk_texts_batch_multiple: Batch chunk multiple texts' do
    result = Kreuzberg.extract_file('', Kreuzberg::ExtractionConfig.new(max_characters: 100))
    expect(result).not_to be_nil
  end
end
