# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:696588455747403fbaf2a0845e441232eaa80c153d8216fddbd9b601c794d8b7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'

RSpec.describe 'document' do
  it 'doc_metadata_docx: Extract DOCX metadata' do
    result = Kreuzberg.extract_file_sync('vendored/markitdown/test.docx')
    expect(result.metadata).not_to be_empty
  end

  it 'doc_metadata_pdf: Extract PDF metadata' do
    result = Kreuzberg.extract_file_sync('pdf/fake_memo.pdf')
    expect(result.metadata).not_to be_empty
  end

  it 'doc_structure_docx: Extract DOCX document structure with include_document_structure config' do
    result = Kreuzberg.extract_file_sync('vendored/markitdown/test.docx', Kreuzberg::ExtractionConfig.new(include_document_structure: true))
    expect(result.document_structure).not_to be_empty
  end

  it 'doc_structure_html: Extract HTML document structure with include_document_structure config' do
    result = Kreuzberg.extract_file_sync('html/html.html', Kreuzberg::ExtractionConfig.new(include_document_structure: true))
    expect(result.document_structure).not_to be_empty
  end

  it 'doc_structure_pdf: Extract PDF document structure with include_document_structure config' do
    result = Kreuzberg.extract_file_sync('pdf/fake_memo.pdf', Kreuzberg::ExtractionConfig.new(include_document_structure: true))
    expect(result.document_structure).not_to be_empty
  end
end
