# frozen_string_literal: true

# Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
# To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang ruby
#
# Tests for email fixtures.

# rubocop:disable Metrics/BlockLength
require_relative 'spec_helper'

RSpec.describe 'email fixtures' do
  it 'email_eml_html_body' do
    E2ERuby.run_fixture(
      'email_eml_html_body',
      'email/html_only.eml',
      nil,
      requirements: [],
      notes: nil,
      skip_if_missing: true
    ) do |result|
      E2ERuby::Assertions.assert_expected_mime(
        result,
        ['message/rfc822']
      )
      E2ERuby::Assertions.assert_min_content_length(result, 10)
    end
  end

  it 'email_eml_multipart' do
    E2ERuby.run_fixture(
      'email_eml_multipart',
      'email/html_email_multipart.eml',
      nil,
      requirements: [],
      notes: nil,
      skip_if_missing: true
    ) do |result|
      E2ERuby::Assertions.assert_expected_mime(
        result,
        ['message/rfc822']
      )
      E2ERuby::Assertions.assert_min_content_length(result, 10)
    end
  end

  it 'email_eml_utf16' do
    E2ERuby.run_fixture(
      'email_eml_utf16',
      'vendored/unstructured/eml/fake-email-utf-16.eml',
      nil,
      requirements: [],
      notes: nil,
      skip_if_missing: true
    ) do |result|
      E2ERuby::Assertions.assert_expected_mime(
        result,
        ['message/rfc822']
      )
      E2ERuby::Assertions.assert_min_content_length(result, 50)
      E2ERuby::Assertions.assert_content_contains_any(result, ['Test Email', 'Roses are red'])
    end
  end

  it 'email_msg_basic' do
    E2ERuby.run_fixture(
      'email_msg_basic',
      'email/fake_email.msg',
      nil,
      requirements: [],
      notes: nil,
      skip_if_missing: true
    ) do |result|
      E2ERuby::Assertions.assert_expected_mime(
        result,
        ['application/vnd.ms-outlook']
      )
      E2ERuby::Assertions.assert_min_content_length(result, 10)
    end
  end

  it 'email_sample_eml' do
    E2ERuby.run_fixture(
      'email_sample_eml',
      'email/sample_email.eml',
      nil,
      requirements: [],
      notes: nil,
      skip_if_missing: true
    ) do |result|
      E2ERuby::Assertions.assert_expected_mime(
        result,
        ['message/rfc822']
      )
      E2ERuby::Assertions.assert_min_content_length(result, 20)
    end
  end
end
# rubocop:enable Metrics/BlockLength
