# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9102db18fdc9e489c1f790726d57730359aab3e9a7bbd801cc15713c3f7c40f6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'format_specific' do
  it 'format_docx_standalone: Standalone DOCX extraction using extract_bytes_sync' do
    data = File.read("docx/fake.docx").bytes
    result = Kreuzberg.extract_bytes_sync(data, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')
    expect(result.content.length).to be >= 20

  end

  it 'format_pdf_text: Standalone PDF text extraction using extract_bytes_sync' do
    data = File.read("pdf/fake_memo.pdf").bytes
    result = Kreuzberg.extract_bytes_sync(data, 'application/pdf')
    expect(result.content.length).to be >= 50
    expect(['Mallori', 'May'].any? { |v| result.content.to_s.include?(v) }).to be(true)

  end

  it 'format_pptx: PPTX presentation extraction using extract_file_sync' do
    skip 'Non-HTTP fixture cannot be tested via Net::HTTP'
  end

  it 'format_xlsx: XLSX spreadsheet extraction using extract_file_sync' do
    skip 'Non-HTTP fixture cannot be tested via Net::HTTP'
  end
end
