// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f0d6379bea7e9a417ab1414f4cd2d8712ecb31b55ead851e188d04ac7d818827
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: detection
void main() {
  setUpAll(() async {
    await RustLib.init();
    final _testDocs = Platform.environment['FIXTURES_DIR'] ?? '../../test_documents';
    final _dir = Directory(_testDocs);
    if (_dir.existsSync()) Directory.current = _dir;
  });

  test('Detect HTML MIME from bytes', () async {
    final result = await KreuzbergBridge.detectMimeTypeFromBytes(File('html/html.html').readAsBytesSync());
  });

  test('Detect PDF MIME type from bytes', () async {
    final result = await KreuzbergBridge.detectMimeTypeFromBytes(File('pdf/fake_memo.pdf').readAsBytesSync());
  });

  test('Detect PNG MIME type from bytes', () async {
    final result = await KreuzbergBridge.detectMimeTypeFromBytes(File('images/test_hello_world.png').readAsBytesSync());
  });

  test('get_extensions unknown MIME', () async {
    await expectLater(KreuzbergBridge.getExtensionsForMime('application/x-totally-unknown'), throwsA(anything));
  });

}
