// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:90a63115e777d6e37d8ee284831cb44bf15484bb8df97c33c93b534c4d6ab3f0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzberg/kreuzberg.dart';

// E2e tests for category: detection
void main() {
  test('Detect HTML MIME from bytes', () {
    final result = KreuzbergBridge.detectMimeTypeFromBytes();
  });

  test('Detect PDF MIME type from bytes', () {
    final result = KreuzbergBridge.detectMimeTypeFromBytes();
  });

  test('Detect PNG MIME type from bytes', () {
    final result = KreuzbergBridge.detectMimeTypeFromBytes();
  });

  test('get_extensions unknown MIME', () {
    final result = KreuzbergBridge.getExtensionsForMime('application/x-totally-unknown');
  });

}
