// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d659eeb63887e340e76cf21abfbf83a8fa1cf026feb1d64cdb8904788ed4ed9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: registry_operations
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Get file extensions for DOCX MIME type', () async {
    final result = await KreuzbergBridge.getExtensionsForMime('application/vnd.openxmlformats-officedocument.wordprocessingml.document');
  });

  test('Get file extensions for HTML MIME type', () async {
    final result = await KreuzbergBridge.getExtensionsForMime('text/html');
  });

  test('Get file extensions for PDF MIME type', () async {
    final result = await KreuzbergBridge.getExtensionsForMime('application/pdf');
    expect(result, contains('pdf'));
  });

}
