// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5d5410b7faf28c8dfd297630e239c7a528f84ba458b6b73918b733931aed3ada
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzberg/kreuzberg.dart';

// E2e tests for category: registry
void main() {
  test('List document extractors', () {
    final result = KreuzbergBridge.listDocumentExtractors();
  });

  test('List OCR backends', () {
    final result = KreuzbergBridge.listOcrBackends();
  });

  test('List post-processors', () {
    final result = KreuzbergBridge.listPostProcessors();
  });

  test('List validators', () {
    final result = KreuzbergBridge.listValidators();
  });

}
