// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cb44946b5835e43238cd36114cfd2cb269b86b5a7759d403287156e7faecc2d9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: embedding_backend_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_EmbeddingBackendsClear(t *testing.T) {
	// Clear all embedding backends and verify list is empty
	err := kreuzberg.ClearEmbeddingBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_EmbeddingBackendsList(t *testing.T) {
	// List all registered embedding backends
	_, err := kreuzberg.ListEmbeddingBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
