// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6af38150cae7fa08234226c3e6da28a0d6aecc73eb3dd7c4d73811436aebc433
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: format_specific
package e2e_test

import (
	"encoding/base64"
	"fmt"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_FormatDocxStandalone(t *testing.T) {
	// Standalone DOCX extraction using extract_bytes_sync
	dataBytes, _ := base64.StdEncoding.DecodeString(`docx/fake.docx`)
	result, err := kreuzberg.ExtractBytesSync(dataBytes, `application/vnd.openxmlformats-officedocument.wordprocessingml.document`, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.GreaterOrEqual(t, len(result.Content), 20, "expected length >= 20")
}

func Test_FormatPdfText(t *testing.T) {
	// Standalone PDF text extraction using extract_bytes_sync
	dataBytes, _ := base64.StdEncoding.DecodeString(`pdf/fake_memo.pdf`)
	result, err := kreuzberg.ExtractBytesSync(dataBytes, `application/pdf`, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.GreaterOrEqual(t, len(result.Content), 50, "expected length >= 50")
	{
		found := false
		if strings.Contains(fmt.Sprint(result.Content), `Mallori`) {
			found = true
		}
		if strings.Contains(fmt.Sprint(result.Content), `May`) {
			found = true
		}
		if !found {
			t.Errorf("expected to contain at least one of the specified values")
		}
	}
}

func Test_FormatPptx(t *testing.T) {
	// PPTX presentation extraction using extract_file_sync
	mime_typeVal := `application/vnd.openxmlformats-officedocument.presentationml.presentation`
	_, err := kreuzberg.ExtractFileSync(`pptx/simple.pptx`, &mime_typeVal, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_FormatXlsx(t *testing.T) {
	// XLSX spreadsheet extraction using extract_file_sync
	mime_typeVal := `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`
	_, err := kreuzberg.ExtractFileSync(`xlsx/stanley_cups.xlsx`, &mime_typeVal, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
