// Code generated by alef. DO NOT EDIT.

// E2e tests for category: image
package e2e_test

import (
	"strings"
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_ImageMetadataOnly(t *testing.T) {
	// JPEG image to validate metadata extraction without OCR.
	result, err := kreuzberg.ExtractFile(`images/example.jpg`, htmd.NewExtractionConfig(htmd.WithExtractionConfigDisableOcr(true), htmd.WithExtractionConfigOcr(nil)))
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `image/jpeg` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	// TODO: unsupported assertion type: max_length
}

func Test_ImageSvgBasic(t *testing.T) {
	// SVG image extraction.
	result, err := kreuzberg.ExtractFile(`xml/simple_svg.svg`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `image/svg+xml` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	// TODO: unsupported assertion type: min_length
}
