// Code generated by alef. DO NOT EDIT.

// E2e tests for category: mime_utilities
package e2e_test

import (
	"strings"
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_MimeDetectBytes(t *testing.T) {
	// Detect MIME type from file bytes
	result, err := kreuzberg.ExtractFile("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if !strings.Contains(string(result.Result), `pdf`) {
		t.Errorf("expected to contain %s, got %v", `pdf`, result.Result)
	}
}

func Test_MimeDetectImage(t *testing.T) {
	// Detect MIME type from PNG image bytes
	result, err := kreuzberg.ExtractFile("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if !strings.Contains(string(result.Result), `png`) {
		t.Errorf("expected to contain %s, got %v", `png`, result.Result)
	}
}

func Test_MimeDetectPath(t *testing.T) {
	// Detect MIME type from file path
	result, err := kreuzberg.ExtractFile("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if !strings.Contains(string(result.Result), `text`) {
		t.Errorf("expected to contain %s, got %v", `text`, result.Result)
	}
}

func Test_MimeGetExtensions(t *testing.T) {
	// Get file extensions for a MIME type
	result, err := kreuzberg.ExtractFile("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if !strings.Contains(string(result.Result), `pdf`) {
		t.Errorf("expected to contain %s, got %v", `pdf`, result.Result)
	}
}

func Test_MimeListSupported(t *testing.T) {
	// List all supported MIME types and file extensions
	_, err := kreuzberg.ExtractFile("")
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
