// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c8e92bccd969c9b951548af7ab003158fce0ca438fed753512d0b54992e702d0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: registry
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_ListDocumentExtractors(t *testing.T) {
	// List document extractors
	_, err := kreuzberg.ListDocumentExtractors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListEmbeddingBackends(t *testing.T) {
	// List embedding backends
	_, err := kreuzberg.ListEmbeddingBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListOcrBackends(t *testing.T) {
	// List OCR backends
	_, err := kreuzberg.ListOcrBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListPostProcessors(t *testing.T) {
	// List post-processors
	_, err := kreuzberg.ListPostProcessors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListRenderers(t *testing.T) {
	// List renderers
	_, err := kreuzberg.ListRenderers()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ListValidators(t *testing.T) {
	// List validators
	_, err := kreuzberg.ListValidators()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
