// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:76101aefcc88e36dfe87e3343d8c352b724f1005783b15cf1bba68975d08b48d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: smoke
package e2e_test

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_SmokeCacheNamespace(t *testing.T) {
	// Smoke test: Extraction with cache namespace and TTL configuration
	var config kreuzberg.ExtractionConfig
	if err := json.Unmarshal([]byte(`{"cache_namespace":"test_tenant","cache_ttl_secs":3600,"use_cache":true}`), &config); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	result, err := kreuzberg.ExtractFile(`text/report.txt`, nil, config)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `text/plain` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	assert.GreaterOrEqual(t, len(result.Content), 5, "expected length >= 5")
}

func Test_SmokeDocxBasic(t *testing.T) {
	// Smoke test: DOCX with formatted text
	result, err := kreuzberg.ExtractFile(`docx/fake.docx`, nil, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `application/vnd.openxmlformats-officedocument.wordprocessingml.document` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	assert.GreaterOrEqual(t, len(result.Content), 20, "expected length >= 20")
	{
		found := false
		if strings.Contains(result.Content, `Lorem`) {
			found = true
		}
		if strings.Contains(result.Content, `ipsum`) {
			found = true
		}
		if strings.Contains(result.Content, `document`) {
			found = true
		}
		if strings.Contains(result.Content, `text`) {
			found = true
		}
		if !found {
			t.Errorf("expected to contain at least one of the specified values")
		}
	}
}

func Test_SmokeHtmlBasic(t *testing.T) {
	// Smoke test: HTML table extraction
	result, err := kreuzberg.ExtractFile(`html/simple_table.html`, nil, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `text/html` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	assert.GreaterOrEqual(t, len(result.Content), 10, "expected length >= 10")
	{
		found := false
		if strings.Contains(result.Content, `Sample Data Table`) {
			found = true
		}
		if strings.Contains(result.Content, `Laptop`) {
			found = true
		}
		if strings.Contains(result.Content, `Electronics`) {
			found = true
		}
		if strings.Contains(result.Content, `Product`) {
			found = true
		}
		if !found {
			t.Errorf("expected to contain at least one of the specified values")
		}
	}
}

func Test_SmokeJsonBasic(t *testing.T) {
	// Smoke test: JSON file extraction
	result, err := kreuzberg.ExtractFile(`json/simple.json`, nil, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `application/json` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	assert.GreaterOrEqual(t, len(result.Content), 5, "expected length >= 5")
}

func Test_SmokePdfBasic(t *testing.T) {
	// Smoke test: PDF with simple text extraction
	result, err := kreuzberg.ExtractFile(`pdf/fake_memo.pdf`, nil, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `application/pdf` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	assert.GreaterOrEqual(t, len(result.Content), 50, "expected length >= 50")
	{
		found := false
		if strings.Contains(result.Content, `May 5, 2023`) {
			found = true
		}
		if strings.Contains(result.Content, `To Whom it May Concern`) {
			found = true
		}
		if !found {
			t.Errorf("expected to contain at least one of the specified values")
		}
	}
}

func Test_SmokeTxtBasic(t *testing.T) {
	// Smoke test: Plain text file
	result, err := kreuzberg.ExtractFile(`text/report.txt`, nil, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `text/plain` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	assert.GreaterOrEqual(t, len(result.Content), 5, "expected length >= 5")
}

func Test_SmokeXlsxBasic(t *testing.T) {
	// Smoke test: XLSX with basic spreadsheet data including tables
	result, err := kreuzberg.ExtractFile(`xlsx/stanley_cups.xlsx`, nil, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(result.MimeType) != `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	assert.GreaterOrEqual(t, len(result.Content), 100, "expected length >= 100")
	if !strings.Contains(string(result.Content), `Team`) {
		t.Errorf("expected to contain %s", `Team`)
	}
	if !strings.Contains(string(result.Content), `Location`) {
		t.Errorf("expected to contain %s", `Location`)
	}
	if !strings.Contains(string(result.Content), `Stanley Cups`) {
		t.Errorf("expected to contain %s", `Stanley Cups`)
	}
	if !strings.Contains(string(result.Content), `Blues`) {
		t.Errorf("expected to contain %s", `Blues`)
	}
	if !strings.Contains(string(result.Content), `Flyers`) {
		t.Errorf("expected to contain %s", `Flyers`)
	}
	if !strings.Contains(string(result.Content), `Maple Leafs`) {
		t.Errorf("expected to contain %s", `Maple Leafs`)
	}
	if !strings.Contains(string(result.Content), `STL`) {
		t.Errorf("expected to contain %s", `STL`)
	}
	if !strings.Contains(string(result.Content), `PHI`) {
		t.Errorf("expected to contain %s", `PHI`)
	}
	if !strings.Contains(string(result.Content), `TOR`) {
		t.Errorf("expected to contain %s", `TOR`)
	}
	assert.GreaterOrEqual(t, len(result.Tables), 1, "expected at least 1 elements")
	if result.Metadata.SheetCount != nil {
		if *result.Metadata.SheetCount < 2 {
			t.Errorf("expected >= 2, got %v", *result.Metadata.SheetCount)
		}
	}
	if result.Metadata.SheetNames != nil {
		if !strings.Contains(strings.Join(*result.Metadata.SheetNames, " "), `Stanley Cups`) {
			t.Errorf("expected to contain %s", `Stanley Cups`)
		}
	}
}
